docker-compose-testnet.yml
docker-compose.yml

On SELinux enables systems, a developer needs to [explicitly instruct Docker/Podman to set the appropriate SELinux label for bind-mounted volumes](https://blog.christophersmart.com/2021/01/31/podman-volumes-and-selinux/).
TODO:

Make docker compose config SELinux aware

---

package.json
src/app/pages/StakingPage/Features/ValidatorMediaInfo/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorMediaInfo/__tests__/index.test.tsx
src/app/pages/StakingPage/Features/ValidatorMediaInfo/index.tsx
yarn.lock

fix: protect validator-media-info from xss attacks

---

src/vendors/explorer/apis/AccountsApi.ts

hotfix: Return empty list of validators, if oasismonitor.com is down

---

src/app/state/staking/saga.ts

Mitigates https://github.com/oasisprotocol/oasis-wallet-web/issues/282
But https://monitor.oasis.dev/data/validators?limit=500 unexpectedly returns 134 rows (18 inactive), not 110 :shrug:

state/staking: show first 500 validators instead of 50

---

src/app/components/MnemonicGrid/index.tsx
src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromMnemonic/index.tsx

Revisits / related to https://github.com/oasisprotocol/oasis-wallet-web/issues/326, https://github.com/oasisprotocol/oasis-wallet-web/pull/331, https://github.com/oasisprotocol/oasis-wallet-web/pull/333.
- This is a stricter version of [#331](https://github.com/oasisprotocol/oasis-wallet-web/pull/331) `/\s/` == `\f\n\r\t\v\u00A0\u2028\u2029`
- I don't like that double-spaces are invalid. Meanwhile, MnemonicGrid was already showing double-space as if it was valid, but submitting it failed.
- And writing whole mnemonic with newlines should have a meaningful validation warning, but converting it just seems easier.

Allow double spaces and newlines in mnemonic

---

src/app/pages/OpenWalletPage/index.tsx

Ledger button was not inlined before so it stretched horizontally on smaller screens. This PR makes it inline using the `Text` grommet component.
|----------|--------|
| ![image](https://user-images.githubusercontent.com/83672/145394669-815b9325-2ccd-4c06-9dd9-17814d8c76d9.png) | ![image](https://user-images.githubusercontent.com/83672/145394341-0d9f226c-f660-49fe-bf63-425942e1b44b.png) |

OpenWallet: Make "Ledger" button responsive the same as others

---

src/app/pages/OpenWalletPage/index.tsx

Oasis Web Wallet issues have been moved to a more common FAQ page at https://docs.oasis.dev/general/manage-tokens/faq. This PR updates the link in the BitPie warning.

OpenWallet: Update link to BitPie FAQ page

---

.vscode/settings.json
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/index.tsx
src/app/pages/StakingPage/Features/ValidatorList/index.tsx
src/types/TypeSafeDataTable.tsx

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/544
Related https://github.com/oasisprotocol/oasis-wallet-web/pull/457
- Added native lazy loading to logos
- All validator rows were destroyed and recreated because `keyField` on rows and `id` on cols were missing
- Show validator logos in DelegationList

Fix validator logos reloading on expand

---

src/app/components/Modal/index.tsx
src/app/pages/AccountPage/Features/SendTransaction/__tests__/index.test.tsx
src/app/pages/AccountPage/Features/SendTransaction/index.tsx
src/index.tsx
src/locales/en/translation.json

Targets #567 
- add ability to run dialogs (I hope I did not reinvent a wheel)
- I wasn't able to add proper component tests. I cannot pass anything to store via configureAppStore due to injected reducers pattern (probably). This throws warnings in other places as well, but due to --silent flag it's not visible. Dispatching `updateValidators` did not resolve that issue. I am missing something probably 🤷‍♂️

Send transaction confirmation dialog

---

src/locales/en/translation.json

this is actually coming up a lot, with a problem on the validators API that we use. the error message incorrectly said "transactions" instead of "validators"

locales/en: correct validator loading error

---

.vscode/settings.json
src/app/pages/StakingPage/Features/CommissionBounds/index.tsx
src/app/state/staking/saga.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/501

Clone bounds before sorting (fixes error mutating readonly props)

---

src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx
src/locales/en/translation.json
src/locales/fr/translation.json

When accessing the web wallet, the user has to re-authenticate often by either inputting the mnemonic, or private key. Since private keys are especially sensitive and often copied from a password manager (where they are hidden), I found myself wanting to keep the private key hidden during import into the web wallet as well. 
The private key was entered into a text area which displayed the private key to the user.
The private key is entered into a text input which hides the private key by default. The user can choose to show the private key by clicking a button beside the text input.
- Changed `TextArea` to `TextInput` to allow input to be classified as a password and hidden
- Added a hide/show private key toggle to the `TextInput`
- Updated jest snapshot to reflect changes
- Updated …

Hide private key by default when importing wallet

---

src/app/components/ErrorFormatter/index.tsx
src/app/lib/ledger.test.ts
src/app/lib/ledger.ts
src/app/state/ledger/saga.test.ts
src/app/state/ledger/saga.ts
src/locales/en/translation.json
src/types/errors.ts

Before - `TransportWebUSB.create` caught TypeError
After - `TransportWebUSB.isSupported`
Before - `publicKey (0x05 0x01 0 0 path)` command failed against the open app:
After - `appName` is not "Oasis":

Improve Ledger errors

---

.github/workflows/build-test.yaml
docker/envoy.yaml
src/app/components/Toolbar/Features/NetworkSelector/__tests__/index.test.tsx
src/app/state/network/index.ts
src/app/state/network/saga.ts
src/app/state/network/types.ts

Genesis rarely changes, and it is pretty heavy.
Switch to consensusGetChainContext, stakingTokenSymbol, and ~hardcode min_delegation~ stakingConsensusParameters

Avoid using consensusGetGenesisDocument

---

src/app/lib/ledger.test.ts
src/app/lib/ledger.ts
src/app/lib/transaction.spec.ts

Previously mistakes in these tests would still pass and just print UnhandledPromiseRejectionWarning, Expected value, Received value

Fix waiting in async tests (wait for expect.resolves / rejects)

---

src/app/components/ShortAddress/__tests__/index.test.tsx
src/app/components/ShortAddress/index.tsx
src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Transaction/__tests__/index.test.tsx
src/app/components/Transaction/index.tsx
src/locales/en/translation.json

This is causing app crash. oasisscan for types like `ExecutorCommit`, `PVSSCommit`  (and more) can return `to: null`  in payload 
https://api.oasisscan.com/mainnet/chain/transactions?size=20&address=oasis1qz5eut7wc0q4ch8ufe8jlrh2qr5n00arc5y7ywht&runtime=false
Needed for #704

Oasisscan: add guards around short address creation

---

internals/getBuildData.js
src/app/components/Footer/__tests__/index.test.tsx
src/app/components/Footer/index.tsx
src/locales/fr/translation.json

Use full sha in href, short in label
`https://github.com/oasisprotocol/oasis-wallet-web/commit/454be7b`
vs
`https://github.com/oasisprotocol/oasis-wallet-web/commit/454be7b0a698e32130c2e0e7a5cabcff3d578242`

Use long revision sha in app footer link

---

package.json
src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Transaction/__tests__/index.test.tsx
src/app/components/Transaction/index.tsx
src/app/pages/AccountPage/Features/TransactionHistory/index.tsx
src/app/state/network/saga.ts
src/config.ts
src/vendors/backend.ts
yarn.lock

Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/747
- handle block explorer links correctly for mainnet and testnet
- added ts-jest dependency to handle mock types nicely. I will create ticket on our board to remove this after Parcel migration. Currently due to old `react-scripts` we are using old Jest version. In the new one mocked function was moved from ts-test/utils into Jest.

Ensure block explorer link goes to the correct block explorer

---

src/app/components/Footer/__tests__/index.test.tsx
src/app/components/Footer/index.tsx
src/locales/en/translation.json
src/locales/fr/translation.json

Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/724
Added a task to an internal board to mock react-i18next globally, because it looks like mocking translations in tests is pattern we  want to follow in this repo.

Add backend name in the app footer

---

src/app/components/Sidebar/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Sidebar/index.tsx

I am not using Grommet Anchor component, because it applies different styles to an icon and it all looks completely different than other icons used in a side bar.

Link from web wallet back to GitHub repo

---

src/app/components/ErrorFormatter/index.tsx
src/app/lib/transaction.spec.ts
src/app/lib/transaction.ts
src/locales/en/translation.json
src/types/errors.ts
yarn.lock

Since https://github.com/oasisprotocol/oasis-sdk/pull/676 all RPC resulted in `Unknown error: Unknown error`

Fix handling wrapped RPC errors

---

internals/scripts/dump_validators.ts
package.json
src/app/components/AddEscrowForm/__tests__/index.test.tsx
src/app/components/AddEscrowForm/index.tsx
src/app/components/Modal/index.tsx
src/app/pages/StakingPage/Features/ValidatorList/ValidatorItem.tsx
src/app/pages/StakingPage/Features/ValidatorList/ValidatorStatus.tsx
src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorList/__tests__/index.test.tsx
src/app/pages/StakingPage/Features/ValidatorList/index.tsx
src/app/state/staking/index.ts
src/app/state/staking/selectors.ts
src/app/state/staking/types.ts
src/locales/en/translation.json
src/locales/fr/translation.json
src/vendors/helpers.ts
src/vendors/oasisscan/dump_validators.json

Part of https://github.com/oasisprotocol/oasis-wallet-web/issues/751
Part of https://github.com/oasisprotocol/oasis-wallet-web/issues/749
Currently, oasisscan is down, and oasismonitor is not loading validators.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3758846/156840108-6c72d826-ec3a-4cef-aedd-f146a44e0acf.png)  | ![localhost_3000_account_oasis1qp25k3hv6ysrm6wntjnt6x0j5du0ud4qqchplrf2_stake (1)](https://user-images.githubusercontent.com/3758846/157794550-2fd1b23d-a476-4cb9-b1dd-e236ff38180a.png) |
|  |  ![localhost_3000_account_oasis1qp25k3hv6ysrm6wntjnt6x0j5du0ud4qqchplrf2_stake (2)](https://user-images.githubusercontent.com/3758846/157794552-e270febd-7e97-473c-b9d7-b14c45621512.png) |

Dump validators list from oasisscan and use as fallback

---

src/app/components/Modal/index.tsx

| --- | --- |
|  ![image](https://user-images.githubusercontent.com/3758846/160038208-76cd478e-6f8a-499a-b783-12c4846a5449.png) |  ![image](https://user-images.githubusercontent.com/3758846/160038147-87d1723e-4c60-4e41-b7b5-9a486a26619d.png) | 
| ![image](https://user-images.githubusercontent.com/3758846/160038268-ab171754-64c0-4892-bc66-7fbcb6621b33.png) | ![image](https://user-images.githubusercontent.com/3758846/160038268-ab171754-64c0-4892-bc66-7fbcb6621b33.png) |

Restyle confirmation modal to match transaction preview modal

---

.parcelrc
extension/src/popup.html
extension/src/popup/popup.tsx
internals/getCsp.js
internals/scripts/serve-prod.js
package.json
src/app/components/Sidebar/index.tsx
src/store/reducers.ts
src/types/env.d.ts
src/types/images.d.ts
tsconfig.json
yarn.lock

PR fixes small issues around extension dev build and allows to render current stuff in popup 
- fixes aliases and adds one missing alias
- fixes CSP, extension requires protocols. added web sockets as well which is required by runtime or hmr (to be determined)
- support for browser routing in extension (at least for now, there is additional ENV, but it really depends on routing strategy)
Questions:
1) How we want to handle routing in extension? Current ext use old hash router, do we want to switch to browser router? Do we want to have exact the same routes in web and ext or routes are define individually in each app?
2) Does anyone build redux-injectors and webext-redux combo? I am not sure proxy store will work
3) Are we aiming for 1:1 implementation, so reducers configuration is in one …

Render wallet app in extension popup

---

internals/generators/component/index.test.tsx.hbs
src/__mocks__/react-i18next.js
src/app/components/AddEscrowForm/__tests__/index.test.tsx
src/app/components/ReclaimEscrowForm/__tests__/index.test.tsx
src/app/components/ShortAddress/__tests__/index.test.tsx
src/app/components/Sidebar/__tests__/index.test.tsx
src/app/components/Toolbar/Features/AccountSelector/__tests__/index.test.tsx
src/app/components/Toolbar/Features/NetworkSelector/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/NetworkSelector/__tests__/index.test.tsx
src/app/components/Toolbar/Features/SearchAddress/__tests__/index.test.tsx
src/app/components/Toolbar/__tests__/index.test.tsx
src/app/components/TransactionModal/__tests__/index.test.tsx
src/app/pages/AccountPage/Features/SendTransaction/__tests__/index.test.tsx
src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/CreateWalletPage/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/index.test.tsx
src/app/pages/StakingPage/Features/CommissionBounds/__tests__/index.test.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/ActiveDelegationList.test.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/DebondingDelegationList.test.tsx
src/app/pages/StakingPage/Features/ValidatorList/__tests__/index.test.tsx
src/setupTests.ts

PR removes two types of warnings that are thrown when unit tests are running
- `Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`
- `Not implemented: window.scrollTo`
I've copied mock from `react-i18next` repo.  It fixes issue with `undefined` in all places where `Trans` component is used. Instead of adding mock in all places let's add it globally. We can always override it in each test file when needed (`CommissionBounds` is an example where test relies on interpolation/real implementation).

Clean up unit tests warnings

---

cypress/integration/create-wallet.ts
cypress/integration/open-wallet.ts
cypress/integration/scenario-account-switcher.ts
cypress/integration/scenario-transaction.ts
src/app/components/FatalErrorHandler/index.tsx
src/app/components/MnemonicValidation/index.tsx
src/app/components/Toolbar/Features/AccountSelector/index.tsx
src/app/pages/AccountPage/Features/SendTransaction/index.tsx
src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/CreateWalletPage/index.tsx
src/app/pages/HomePage/index.tsx
src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx
src/locales/en/translation.json

Term "account" denotes a keypair corresponding to a single oasis address. The term wallet denotes one or more accounts stored in a file, browser, Ledger, as a mnemonic etc.
Term "open" corresponds to an action where you open something stored in a file or a Ledger device. Term "import" corresponds to an action where you need to type in mnemonics or a private key again in order to access it.
This PR fixes the usage of account/wallet and open/import terms.
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/812

i18n: Fix wrong usage of "wallet" in contrast to "account"

---

src/app/components/AddEscrowForm/__tests__/index.test.tsx
src/app/components/AddEscrowForm/index.tsx
src/app/pages/StakingPage/Features/ValidatorList/ValidatorItem.tsx
src/locales/en/translation.json

Mitigates https://github.com/oasisprotocol/oasis-wallet-web/issues/766

Add a notice before staking to top 20 validators to encourage decentralization

---

.github/workflows/dump-validators.yml

https://github.com/oasisprotocol/oasis-wallet-web/pull/845 didn't run CI actions until closing and reopening it. Added a link to the explanation in https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

Add a tip about running CI in "Update dumped validators" PRs

---

src/app/components/LoadingIndicator/__tests__/index.test.tsx
src/app/components/LoadingIndicator/index.tsx
src/app/components/Toolbar/Features/SearchAddress/SearchBox.tsx
src/app/components/Toolbar/Features/SearchAddress/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/SearchAddress/index.tsx
src/app/components/Toolbar/__tests__/__snapshots__/index.test.tsx.snap
src/styles/global-styles.ts
src/styles/theme/styled.d.ts

| --- | --- |
|  ![before](https://user-images.githubusercontent.com/3758846/171311277-7f62a6d6-69b9-4fba-8de7-351766c9475f.png) | ![after](https://user-images.githubusercontent.com/3758846/171311273-bd8754bd-5ef4-402c-b774-51d9b9a961b3.png)  |

Restyle SearchAddress focus and refactor

---

.eslintignore
.eslintrc.js
.gitignore
internals/extractMessages/i18next-scanner.config.js
internals/getCsp.js
internals/jest/jest.base-config.js
internals/jest/jest.ext-config.js
internals/jest/jest.web-config.js
internals/scripts/serve-prod.js
jest.config.js
package.json
posthtml.config.js
src/__mocks__/react-i18next.js

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/774 again. After merging https://github.com/oasisprotocol/oasis-wallet-web/pull/855, megalinter on master checked all files and failed.
This was because:
- `yarn lint` used `.eslintrc.js` rules on only js,ts,tsx files in `./src` and `./extension/src`
- megalinter on a pullrequest used `.eslintrc.js` only on changed js,ts,tsx files
- megalinter on master used `eslintrc.js` on all js,ts,tsx files
After:
- `.eslintignore` is symlinked to `.gitignore`
- `yarn lint` uses `.eslintrc.js` on all js,ts,tsx files, except gitignored ones
- megalinter on a pullrequest still uses `.eslintrc.js` only on changed js,ts,tsx files
- megalinter on master still uses `eslintrc.js` on all js,ts,tsx files

Configure lint for all files, to match megalinter

---

src/app/components/Sidebar/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Sidebar/index.tsx
src/app/components/Toolbar/index.tsx
src/app/pages/AccountPage/Features/AccountDetails/index.tsx
src/app/pages/AccountPage/Features/AccountSummary/index.tsx
src/app/pages/AccountPage/index.tsx
src/app/pages/StakingPage/Features/ValidatorList/index.tsx
src/app/state/wallet/selectors.ts

I suggest reviewing differences commit by commit, and ignoring whitespace changes
| Tabbing through sidebar buttons before | After |
| --- | --- |
|  ![before](https://user-images.githubusercontent.com/3758846/166311836-d3dbd143-8f29-457a-9e58-87a3b3cb14b5.gif) | ![after](https://user-images.githubusercontent.com/3758846/166311832-07122d34-6a63-4e24-9a60-c7586b94dd41.gif)  |

Refactor sidebar and make all buttons focusable

---

src/app/pages/AccountPage/Features/AccountDetails/index.tsx
src/app/pages/AccountPage/Features/SendTransaction/__tests__/index.test.tsx
src/app/pages/AccountPage/Features/SendTransaction/index.tsx

Before: 
- user imports `oasis1qqug..hsu8` to wallet
- search `oasis1qr9t..gxfl`
- see SendTransaction component to transfer from `oasis1qqug..hsu8` to any _Recipient_

Only show SendTransaction on your accounts

---

.github/workflows/build-test.yaml

`jest` and `cypress` steps didn't really need to wait for `build`. But if they didn't wait, then `gha-yarn-cache` would save cache three times.
`yarn_cache` should only save cache once and speed up CI by 2min when cache is hit and 40sec when missed

Speedup caching in CI

---

renovate.json

Whenever we merge a Renovate PR, all others get rebased and spam CI. So waiting for CI and merging one by one is slow. We can group some of these PRs by package name, and be happier until an update breaks things https://docs.renovatebot.com/noise-reduction/#package-grouping

Combine packages into groups in Renovate to reduce PR clutter

---

src/app/state/account/saga.test.ts
src/app/state/account/saga.ts
src/app/state/network/saga.test.ts
src/app/state/network/saga.ts
src/app/state/staking/saga.test.ts
src/app/state/staking/saga.ts

Prevent race conditions when loading account

---

src/app/components/AlertBox/index.tsx
src/app/components/ErrorFormatter/index.tsx
src/app/components/FatalErrorHandler/index.tsx
src/app/components/TransactionModal/index.tsx
src/app/components/TransactionStatus/index.tsx
src/app/pages/AccountPage/Features/AccountSummary/index.tsx
src/app/pages/AccountPage/Features/TransactionHistory/index.tsx
src/app/pages/AccountPage/index.tsx
src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/CreateWalletPage/index.tsx
src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/ActiveDelegationList.test.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/DebondingDelegationList.test.tsx
src/app/pages/StakingPage/Features/ValidatorList/index.tsx
src/app/state/account/index.ts
src/app/state/account/saga.ts
src/app/state/account/types.ts
src/app/state/staking/index.ts
src/app/state/staking/saga.test.ts
src/app/state/staking/saga.ts
src/app/state/staking/types.ts
src/locales/en/translation.json
src/types/errors.ts
src/vendors/__tests__/throwAPIErrors.test.ts
src/vendors/explorer/runtime.ts
src/vendors/helpers.ts
src/vendors/monitor.ts
src/vendors/oasisscan.ts

Related to https://github.com/oasisprotocol/oasis-wallet-web/issues/403
- Revert https://github.com/oasisprotocol/oasis-wallet-web/commit/8c483c0e47f2108a7b8e41dcf13be1c94ba04c3f and use middleware to throw IndexerAPIError instead.
(related https://github.com/oasisprotocol/oasis-wallet-web/commit/cac52d18004c14704647a623d58f8c729e243331 and https://github.com/oasisprotocol/oasis-wallet-web/commit/6a59864e01c6896928d94e098d2d8441b820b479)
- Use the same middleware for oasisscan too
- Survive getting delegations failures
- Simplify displayed text of existing "survivable" errors and tell users to come back :pleading_face: 
| --- | --- |
| Loading delegations error: | |
| ![delegations_before](https://user-images.githubusercontent.com/3758846/175657176-0b63a2b9-96f9-4707-9cd …

Survive fetching delegations failures

---

extension/src/background.html
internals/getBuildData.js
internals/prod-ext.js
internals/prod-web.js
package.json
public/manifest.json

Targets #853 
So far I found three workarounds:
1. Init background via background `page` instead of `scripts` array. Compiled html has all chunks and issue with chunks is fixed.
Other workarounds:
2. kill chunks/code split, which is controlled by entry in [package.json](https://parceljs.org/features/code-splitting/#configuration)
```
"@parcel/bundler-default": {
"minBundles": 10 // some magic number
}
```
3. Do not share deps between popup and background (avoid shared chunk) for example by using dynamically imported modules. This can be achieved in different ways probably and would allow us to keep chunks that will work in FF.
Without going too deep in debugging I think background script was executed without runtime (or shared modules), or before runtime was initialised and because of bg …

Fix extension production build errors and inject missing env variables

---

src/app/components/AddEscrowForm/index.tsx
src/app/components/Sidebar/index.tsx
src/app/pages/AccountPage/Features/AccountDetails/index.tsx
src/app/pages/StakingPage/Features/DelegationList/index.tsx
src/app/pages/StakingPage/Features/ValidatorList/ValidatorItem.tsx
src/app/pages/StakingPage/Features/ValidatorList/index.tsx
src/app/state/selectIsAddressInWallet.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/917
| --- | --- |
| ![before](https://user-images.githubusercontent.com/3758846/177892291-457f4046-199f-4350-8aa0-636d1ea569fe.png)  |  ![after](https://user-images.githubusercontent.com/3758846/177892288-03329e53-fefa-4dd3-8102-201ee53b3f5c.png) |

Only show AddEscrowForm on your accounts

---

src/locales/__tests__/strict-translation-keys.test.tsx
src/locales/i18n.ts
src/types/TypeSafeDataTable.tsx
src/types/__tests__/TypeSafeDataTable.test.tsx
src/utils/@reduxjs/toolkit.test.tsx

Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/911

Test our type-safe replacements

---

src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/AccountSelector/__tests__/index.test.tsx
src/app/components/Toolbar/Features/AccountSelector/index.tsx
src/app/lib/helpers.test.ts
src/app/lib/helpers.ts
src/app/pages/AccountPage/index.tsx
src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
src/app/state/wallet/saga.test.ts
src/app/state/wallet/selectors.ts
src/app/state/wallet/types.ts

Stop using misleading `total` field from parseRpcBalance, remove it, and group validator-specific fields. In the future we should convert some of these RPC calls to API calls and use correct `total`
| Before `available + escrow (validator) + escrow_debonding (validator)` | After `available` |
| --- | --- |
|  ![before](https://user-images.githubusercontent.com/3758846/178626051-a10f66a7-58f9-4de3-8593-178ce712e192.png) | ![after](https://user-images.githubusercontent.com/3758846/178626048-d05127a6-9d4f-44d4-87a6-98b84d23e4b0.png)  |

Don't use misleading balance fields from RPC

---

src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Footer/__tests__/index.test.tsx
src/app/components/Footer/index.tsx
src/app/components/MobileFooterNavigation/__tests__/index.test.tsx
src/app/components/MobileFooterNavigation/index.tsx

- add fixed menu to footer
- tweak footer css for mobile

Change UI to be more similar to current extension: footer

---

src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/AccountPage/index.tsx
src/locales/en/translation.json
src/locales/fr/translation.json
src/locales/sl/translation.json
src/locales/tr/translation.json

PR updates styles of Transaction List subnav. Once merge I will have to sync translations files via Transifex. In next iteration this menu will be moved from Account to Stake page.

Change UI to be more similar to current extension: Account Page subnav 

---

src/app/components/TimeToEpoch/__tests__/index.test.tsx
src/app/components/TimeToEpoch/index.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/index.tsx
src/locales/en/translation.json

Related to https://github.com/oasisprotocol/oasis-wallet-web/issues/420
| --- | --- |
|  ![1](https://user-images.githubusercontent.com/3758846/183716051-0ccc347e-f5ea-41fb-9c41-c3723001675b.png) |  ![2](https://user-images.githubusercontent.com/3758846/183716054-c58f9f02-aeb7-44ea-b740-db3f931c5a1d.png) |

Display estimated debonding time in debonding list

---

src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Transaction/index.tsx
src/locales/en/translation.json
src/locales/fr/translation.json
src/locales/sl/translation.json
src/locales/tr/translation.json

Partially addresses https://github.com/oasisprotocol/oasis-wallet-web/issues/752
| --- | --- |
| ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90 (1)](https://user-images.githubusercontent.com/3758846/182986071-c1c7db82-dbe7-4900-977e-659d2f4521c5.png)  | ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90](https://user-images.githubusercontent.com/3758846/182986068-bc6f9617-1aef-437f-9a42-d991c038e9bd.png)  |

Improve descriptions of transactions

---

src/app/pages/ParaTimesPage/ParaTimeContent/index.tsx
src/app/pages/ParaTimesPage/ParaTimeSelection/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/ParaTimeSelection/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/ParaTimeTransferType/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/ParaTimeTransferType/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/ParaTimeTransferType/index.tsx
src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/index.tsx
src/app/pages/ParaTimesPage/TransactionAmount/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionAmount/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/TransactionSummary/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionSummary/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/index.tsx
src/app/pages/ParaTimesPage/useParaTimes.test.ts
src/app/pages/ParaTimesPage/useParaTimes.ts
src/app/pages/ParaTimesPage/useParaTimesNavigation.test.ts
src/app/pages/ParaTimesPage/useParaTimesNavigation.ts
src/app/state/paratimes/saga.test.ts
src/app/state/paratimes/saga.ts
src/locales/en/translation.json
src/store/__tests__/reducer.test.ts

Tests around
- form steps components/ unmocking `react-i18next` in a few tests to validate conditional interpolation
- paraTime saga 
- useParaTimesNavigation
- useParaTimes
PR adds:
- restriction around paratime route

ParaTimes: unit tests

---

src/app/components/ShortAddress/__tests__/index.test.tsx
src/app/components/ShortAddress/index.tsx

... so that it doesn't "trim" strings in a way which makes them longer.
(Also improve the tests a bit.)
Fixes #950

Improve the trimLongStart function

---

src/app/components/ShortAddress/__tests__/index.test.tsx
src/app/components/ShortAddress/index.tsx

... from negative to positive.
Update the tests accordingly.
(Also remove useless comment.)
This is the next step of #1006, Inspired by a comment made by @lukaw3d  [here](https://github.com/oasisprotocol/oasis-wallet-web/pull/1006#discussion_r977092236).

trimLongString(): flip semantics of trimEnd

---

src/app/lib/key.ts

... when doing UInt8Array to string conversion.
This improves upon #1007.

 Make private key testing code more explicit

---

src/app/components/Footer/__tests__/index.test.tsx
src/app/components/MobileFooterNavigation/__tests__/index.test.tsx
src/app/components/Toolbar/Features/AccountSelector/__tests__/index.test.tsx
src/app/components/Toolbar/Features/AccountSelector/index.tsx
src/app/components/TransactionModal/index.tsx
src/app/pages/AccountPage/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
src/app/state/transaction/saga.test.ts
src/app/state/wallet/index.ts
src/app/state/wallet/saga.test.ts
src/app/state/wallet/saga.ts
src/app/state/wallet/selectors.ts
src/app/state/wallet/types.ts
src/app/useRouteRedirects.test.ts
src/app/useRouteRedirects.tsx

Motivation: `let walletId = 0` is annoying to add to persisted state

Remove global walletId and index accounts by address

---

extension/src/popup.html
src/app/components/Header/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Header/__tests__/index.test.tsx
src/app/components/Header/index.tsx
src/app/components/MnemonicValidation/index.tsx
src/app/components/Modal/index.tsx
src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/AccountSelector/index.tsx
src/app/components/TransactionModal/index.tsx
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/AccountPage/index.tsx
src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/CreateWalletPage/index.tsx
src/app/pages/HomePage/index.tsx
src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
src/app/pages/OpenWalletPage/index.tsx
src/app/pages/StakingPage/Features/DelegationList/ActiveDelegationList.tsx
src/app/pages/StakingPage/Features/DelegationList/DebondingDelegationList.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorList/ValidatorInformations.tsx
src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorList/index.tsx

- new popup dimensions
- responsive headers, unify usage of main and modal headers. Headers were not responsive because they were using sanitize.css not Grommet rules because of wrong syntax like `<Heading size="1"> `
- fixes: unify Box paddings in main pages a little bit, change alignment of buttons in modal windows, AccountPage sub menu nav, PrivateKey input width
current ext
updated
current desktop (just 1 sample, but most of current headers look differently)
updated

UI tweaks for extension and mobile

---

.gitignore

These are various temp files that are sometimes used by Emacs and other editors.

Ignore temporary / editor files

---

src/app/components/PasswordField/__tests__/index.test.tsx
src/app/components/PasswordField/__tests__/type-only.test.tsx
src/app/components/PasswordField/index.tsx
src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx

I tried to make validation part of the input field, so that onSubmit doesn't need to re-check validity of every input field. But then error-specific-styling doesn't work `contentProps={{ border: props.error ? 'bottom' : false }}`.
| --- | --- |
|  ![localhost_3000_open-wallet_private-key (2)](https://user-images.githubusercontent.com/3758846/195467451-f714d627-61fa-4a38-9925-5c31ac22e8e1.png) | ![localhost_3000_open-wallet_private-key](https://user-images.githubusercontent.com/3758846/195467450-b9a415f1-2a33-4f30-b544-95e98a81744f.png)  |

Refactor password field validation and restyle

---

cypress/e2e/home.cy.ts
cypress/e2e/open-wallet.cy.ts
cypress/e2e/scenario-account-switcher.cy.ts
cypress/e2e/scenario-transaction.cy.ts
src/app/components/ButtonLink/index.tsx
src/app/pages/HomePage/index.tsx
src/app/pages/OpenWalletPage/index.tsx

Fixes issues:
- Keyboard navigating through these buttons would first focus on the link, and then on the button
- Multiple buttons were marked as type="submit" without being in multiple forms
- On a small screen "Mnemonic / Private key / Ledger" buttons would collapse into rows of left-aligned buttons, but links would fill up the whole row

Refactor HomePage buttons into ButtonLinks to improve accessibility

---

package.json
src/index.tsx
src/setupTests.ts

Workaround for a transpiler issue with bigints/bigintegers after switching to `@ethereumjs/util` package. After removing these two browsers from `browserlist` extension works correctly.
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1111#issuecomment-1293603751

Remove IE11 and Android 4.4.x from the list of supported browsers

---

extension/src/popup/popup.tsx
extension/src/popup/routes.tsx
internals/jest/jest.base-config.js
package.json
src/app/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Header/__tests__/index.test.tsx
src/app/components/Header/index.tsx
src/app/index.tsx
src/app/lib/ledger.test.ts
src/app/lib/ledger.ts
src/app/pages/AccountPage/__tests__/index.test.tsx
src/app/pages/AccountPage/index.tsx
src/app/pages/ConnectDevicePage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ConnectDevicePage/__tests__/index.test.tsx
src/app/pages/ConnectDevicePage/index.tsx
src/app/pages/OpenWalletPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/index.tsx
src/app/pages/OpenWalletPage/webextension.tsx
src/commonRoutes.tsx
src/index.tsx
src/locales/en/translation.json
src/routes.tsx
src/utils/webextension.test.ts
src/utils/webextension.ts
yarn.lock

Fixes #1045
During sync meeting we decided to go with a popup like in a current ext.
error:

Fix extension WebUSB permission issue

---

src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx

The purpose of setting the min-height was to avoid the buttons jumping while enumerating the accounts.
Unfortunately the previously set value (336px) was not enough in extension mode, so some jumping remained. Adjusting it (to 362px) takes care of this.

Adjust the min-height of the import account dialog

---

extension/src/popup/routes.tsx
src/app/components/ErrorBoundary/index.tsx
src/app/pages/AccountPage/index.tsx
src/commonRoutes.tsx
src/routes.tsx

Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1004#discussion_r979070318
and https://github.com/oasisprotocol/oasis-wallet-web/pull/1079#discussion_r1003929246

Move route address validation from AccountPage into routes

---

src/app/components/ResponsiveLayer/index.tsx

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1056

Fix modals scrolling to top on every selection

---

src/app/components/Transaction/index.tsx
src/app/state/transaction/types.ts
src/vendors/oasisscan.ts
src/vendors/oasisscan/models/OperationsRow.ts
src/vendors/oasisscan/swagger3.yml

CI/CD is failing currently
```
1) by comparing list of methods from oasisscan
AssertionError: expected [ Array(17) ] to have a length of 16 but got 17
```

Update Oasis Scan OperationsRow swagger spec

---

src/app/lib/preventSavingInputsToUserData.ts
src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/__snapshots__/index.test.tsx.snap

Prevent https://www.otto-js.com/news/article/spell-jacking-enhanced-spellcheck-features-send-pii-even-passwords
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1171

Disable spellcheck in sensitive inputs

---

src/app/components/MnemonicGrid/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/MnemonicGrid/__tests__/index.test.tsx
src/app/components/MnemonicGrid/index.tsx
src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap

Quick improvement since https://github.com/oasisprotocol/oasis-wallet-web/pull/1181 disables spell-checking mnemonic
| Before 1181 | After 1181 + this |
| --- | --- |
|  ![localhost_3000_open-wallet_mnemonic (1)](https://user-images.githubusercontent.com/3758846/204437830-17477963-8d7e-4d39-87a8-df1c598ae4ca.png) |  ![localhost_3000_open-wallet_mnemonic](https://user-images.githubusercontent.com/3758846/204437827-6b2fa8a9-4638-4197-adc2-7a2c28793d73.png) |

Validate mnemonic words in MnemonicGrid

---

internals/jest/jest.base-config.js
package.json
src/app/pages/ParaTimesPage/useParaTimes.test.ts
src/app/pages/ParaTimesPage/useParaTimesNavigation.test.ts
src/app/useRouteRedirects.test.ts
yarn.lock

- @testing-library/react-hooks is now consolidated into @testing-library/react
- jest-watch-typeahead was throwing warnings and I doubt anyone uses it much

Remove @testing-library/react-hooks and jest-watch-typeahead

---

.github/workflows/build-test.yaml
.github/workflows/mega-linter.yml
package.json
src/app/components/DateFormatter/index.tsx
yarn.lock

Alternative to https://github.com/oasisprotocol/oasis-wallet-web/pull/1143
Difference: only upgraded parcel and cypress transitive dependencies (by reinstalling parcel and cypress), instead of all transitive dependencies (by recreating yarn.lock)
CI succeeded with these changes:
- node 14 https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/4325660709
- node 16 https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/4325662316
- node 18 https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/4325663345

Upgrade CI to node v18

---

.github/workflows/build-test.yaml
.github/workflows/dump-validators.yml
.github/workflows/mega-linter.yml

Fix MegaLinter error. Currently CI is failing due to  (default `write-all`?) 
```  Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
FAILED for resource: on(Mega-Linter)
File: /.github/workflows/mega-linter.yml:0-1
Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
FAILED for resource: on(dump-validators)
File: /.github/workflows/dump-validators.yml:0-1
Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
FAILED for resource: on(Build and test)
File: /.github/workflows/build-test.yaml:0-1```

Ensure top-level permissions are not set to write-all

---

playwright/package.json
playwright/tests/extension.spec.ts
playwright/tests/persist.spec.ts
playwright/tests/syncTabs.spec.ts
playwright/yarn.lock
src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
src/locales/en/translation.json
src/locales/fr/translation.json
src/locales/sl/translation.json
src/locales/tr/translation.json
src/utils/webextension.test.ts
src/utils/webextension.ts

Related to https://github.com/oasisprotocol/oasis-wallet-ext/pull/302 and https://github.com/oasisprotocol/oasis-wallet-ext/pull/301
| --- | --- |
| ![before](https://user-images.githubusercontent.com/3758846/225198239-08dbe23a-e82c-49cf-bf06-82591ea99fd7.png)  |  ![after](https://user-images.githubusercontent.com/3758846/225198234-9ee14606-ec09-4389-91a3-c55c626fc8fb.png) |

Fix connecting to ledger by opening a normal window, not headless popup

---

playwright/package.json
playwright/yarn.lock

During https://github.com/oasisprotocol/oasis-wallet-web/pull/1321 I needed playwright prerelease to test if popup would ask for permissions after it no longer crashed Chromium.
It did not ask for permissions, so as a workaround I open a normal window instead of a popup. This asks for permissions and doesn't crash Chromium 110.x/111.x. With this workaround we no longer need prerelease, and we can test against latest browsers instead.

Downgrade to latest playwright (ledger window doesn't crash Chromium)

---

playwright/tests/persist.spec.ts
playwright/tests/syncTabs.spec.ts
playwright/utils/expectShell.ts
src/app/state/network/index.ts
src/app/state/network/saga.ts
src/app/state/persist/index.ts
src/app/state/persist/syncTabs.ts

Related to https://github.com/oasisprotocol/oasis-wallet-web/issues/792#issuecomment-1269273318
Reverts part of c125984a415bd1a3fd9dd61c9ce6f2634e8ef8eb and re-fixes https://github.com/oasisprotocol/oasis-wallet-web/pull/975#discussion_r1012328608
Instead of waiting for tabs to be synced before selecting network initially:
- initialize selecting network without syncing that action
- using takeLatest cancel initialization task if tabs sync during selectNetwork

Refactor selecting network initially to avoid sync timing issues

---

src/app/pages/ParaTimesPage/TransactionAmount/index.tsx
src/app/pages/ParaTimesPage/useParaTimes.ts
src/locales/en/translation.json

Currently bug `Unknown gRPC error: client: transaction check failed: runtime error: module: consensus code: 5 message: consensus: amount not representable` can occur during withdraws from EVM ParaTimes.
In both cases, deposit to ParaTime from Consensus and withdraw from ParaTime to Consensus, we need valid Consensus amounts.

ParaTimes: fix Consensus amount not representable bug

---

src/app/lib/__tests__/helpers.test.ts
src/app/lib/__tests__/ledger.test.ts
src/app/lib/__tests__/privateToEthAddress.test.ts

Related to https://github.com/oasisprotocol/explorer/commit/dbdabe6c56bdfc0866e4a86908a65bda551c72c4
Apparently none of our existing jest tests touch multiple imports from `@ethereumjs/util` that check `instanceof Uint8Array` internally. Otherwise we would have odd failures. Added a skipped test as a reminder

Add failing test for privateToEthAddress

---

playwright/playwright.config.ts
playwright/tests/paraTimes.spec.ts
src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/TransactionRecipient/index.tsx

Currently user can navigate back to ParaTime selector step which can lead to weird experience as we keep data for next steps.
sample: fill in Cipher recipient go back to the first step, select emerald, click next and we have Oasis addr in recipient input where we need eth addr.

ParaTimes: cancel transfer instead of navigating back to ParaTime selection

---

src/app/components/Transaction/InfoBox.tsx
src/app/pages/AccountPage/Features/AccountSummary/index.tsx
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
src/app/pages/ParaTimesPage/ParaTimeFormFooter/index.tsx
src/app/pages/ParaTimesPage/ParaTimeSelection/index.tsx
src/app/pages/ParaTimesPage/ParaTimeTransferType/index.tsx
src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/index.tsx
src/app/pages/ParaTimesPage/TransactionAmount/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionAmount/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/TransactionAmount/index.tsx
src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/TransactionConfirmation/index.tsx
src/app/pages/ParaTimesPage/TransactionError/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionError/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/TransactionError/index.tsx
src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionRecipient/index.tsx
src/app/pages/ParaTimesPage/TransactionSummary/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionSummary/index.tsx
src/locales/en/translation.json

This PR fixes inconsistencies of typical ParaTime terms and operations. Also adopts strings for easier translation:
- correctly use terms "account" and "wallet". Wallet = collection of accounts. Empty wallet means there are no accounts in it. Empty account means the balance is zero.
- try to avoid terms "ParaTime" and "token" where possible. e.g. Emerald Paratime -> Emerald or Oasis Emerald. Withdraw 200 ROSE tokens -> Withdraw 200 ROSE.
- there are three types of token transactions currently: transfer (consensus->consensus, ParaTime->ParaTime), deposit (consensus->ParaTime) and withdrawal (ParaTime->consensus). Do not use term "transfer" in the context of deposits/withdrawals.
- for placeholders react-i18next uses {{someTerm}} [without surrounding …

i18n: Make ParaTime terms consistent with docs and Oasis CLI

---

README.md

Badge was updated over a year ago as it runs against `develop`. Based on feedback we don't want to take control over it (currently Esya user is an owner?) because it requires access to entire Oasis Protocol org.

Remove FOSSA from readme

---

playwright/tests/syncTabs.spec.ts
src/app/components/BuildPreviewBanner/index.tsx
src/locales/en/translation.json

Related https://github.com/oasisprotocol/oasis-wallet-web/issues/1410
Will refactor in another PR

Show a new domain banner

---

src/app/pages/ParaTimesPage/ParaTimeSelection/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/ParaTimeSelection/index.tsx
src/styles/theme/ThemeProvider.tsx

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1385
| Placeholder | Options | Value |
| --- | --- | --- |
| ![d80a2c49 oasis-wallet pages dev_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes](https://user-images.githubusercontent.com/3758846/234433560-417c3e89-dddb-420f-b328-4994dda2a786.png) | ![d80a2c49 oasis-wallet pages dev_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes (2)](https://user-images.githubusercontent.com/3758846/234433772-7d75b3c6-4a47-4055-97d4-3961d37e5648.png) | ![d80a2c49 oasis-wallet pages dev_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes (1)](https://user-images.githubusercontent.com/3758846/234433566-26a115d0-55b5-4db3-9303-4f4b60ffe122.png) |

Make ParaTimeSelection padding match placeholder, option, and value

---

src/app/components/AlertBox/index.tsx
src/app/components/BuildPreviewBanner/index.tsx
src/app/components/TransactionStatus/index.tsx
src/app/pages/AccountPage/Features/AccountSummary/index.tsx
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionError/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorList/ValidatorStatus.tsx
src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
src/locales/en/translation.json
src/styles/theme/ThemeProvider.tsx

These better match Transak mocks, and not using transparency gives us better control if we need to change them
| --- | --- |
| ![wallet oasis io_account_oasis1qqfnswjm4l5wcpc0ysz29fg4e85f6uqlasvzyl26](https://user-images.githubusercontent.com/3758846/234441817-802b9e31-dcca-4d93-8f83-9f9227322f9d.png) | ![localhost_3000_account_oasis1qza7np2lcnggvrppgjte7n2c9gkerc5jgsnuuapg](https://user-images.githubusercontent.com/3758846/234441810-6a349fc0-9899-4c35-a183-0f8e5c56a7ef.png) |
| ![wallet oasis io_account_oasis1qqfnswjm4l5wcpc0ysz29fg4e85f6uqlasvzyl26 (1)](https://user-images.githubusercontent.com/3758846/234441819-a4eaa261-7154-4e22-b5dc-35eff92c022b.png) | ![localhost_3000_account_oasis1qza7np2lcnggvrppgjte7n2c9gkerc5jgsnuuapg …

Restyle and refactor alerts

---

src/app/components/AlertBox/index.tsx
src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/MobileFooterNavigation/index.tsx
src/app/components/Sidebar/index.tsx
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/FiatOnramp/index.tsx
src/app/pages/FiatOnramp/isEnabled.ts
src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionError/__tests__/__snapshots__/index.test.tsx.snap
src/commonRoutes.tsx
src/locales/en/translation.json

Before: https://github.com/oasisprotocol/oasis-wallet-web/pull/1357
After:
| Testnet | Bookmarked account | Acknowledge | Loaded | Iframe long height |
| --- | --- | --- | --- | --- |
| ![localhost_3000_account_oasis1qqcu4g9dgq2ajpmeddtzessye9tvnanuws74u6rc_fiat](https://user-images.githubusercontent.com/3758846/234739301-278231fb-775a-4d34-8848-802db248456f.png) | ![localhost_3000_account_oasis1qqcu4g9dgq2ajpmeddtzessye9tvnanuws74u6rc_fiat (1)](https://user-images.githubusercontent.com/3758846/234739306-6a381337-0d09-42b6-8815-b2d8fca3b18f.png) | ![localhost_3000_account_oasis1qqcu4g9dgq2ajpmeddtzessye9tvnanuws74u6rc_fiat (2)](https://user-images.githubusercontent.com/3758846/234739307-58498d86-4ffe-49ee-917f-160f2dc58be1.png) | …

Embed transak iframe in Fiat on-ramp

---

src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/AddEscrowForm/__tests__/index.test.tsx
src/app/components/AlertBox/index.tsx
src/app/components/BuildPreviewBanner/index.tsx
src/app/components/ErrorBoundary/index.tsx
src/app/components/FatalErrorHandler/index.tsx
src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/ReclaimEscrowForm/__tests__/index.test.tsx
src/app/components/TransactionModal/index.tsx
src/app/components/TransactionStatus/index.tsx
src/app/pages/AccountPage/Features/AccountSummary/index.tsx
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/AccountPage/index.tsx
src/app/pages/ConnectDevicePage/index.tsx
src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/CreateWalletPage/index.tsx
src/app/pages/E2EPage/index.tsx
src/app/pages/FiatOnramp/index.tsx
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
src/app/pages/ParaTimesPage/TransactionAmount/index.tsx
src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionConfirmation/index.tsx
src/app/pages/ParaTimesPage/TransactionError/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionError/index.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
src/styles/theme/ThemeProvider.tsx

https://www.figma.com/file/G6EVdJhfGbDBZRdpWnUyC7/Wallet-Design-System?type=design&node-id=22-1429&t=E44uYOZqmDSuC2xp-0
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3758846/236086487-ef0b191c-efdf-4395-af35-b2bd846c9ced.png)  | ![image](https://user-images.githubusercontent.com/3758846/236357132-c843d934-155d-4b9d-9d7a-42a651af9c31.png) |
|  ![a1](https://user-images.githubusercontent.com/3758846/236085311-5c1fa203-2ddc-42ab-917c-1106d95141d9.png) | ![localhost_3000_account_oasis1qrdx0n90qz6d2me83gwdykgfu233x8f6psa4l3vd](https://user-images.githubusercontent.com/3758846/236357359-0aec0b38-cde3-44e4-be2f-26dee32111f7.png) |
| ![a2](https://user-images.githubusercontent.com/3758846/236085312-02226090-6035-47d6-a170-6ef7c4f76425.png) | …

Update AlertBox colors

---

src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/AccountPage/index.tsx
src/styles/theme/ThemeProvider.tsx
src/styles/theme/elementSizes.ts

Refactored using grommet's badge on a button that doesn't use z-index
| --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_stake (5)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/39487894-5d5b-426c-8aed-195fa9ddae58)  |  ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_stake (3)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/ccb44984-9d83-4aa8-accc-a80f51710e18) |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_stake (4)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/3c0e8e47-e667-436d-8a42-6f0ccdd620a0) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_stake …

Fix badge counter z-index being above preview banner

---

docs/release-process.md
package.json

Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1447
(Cloudflare configuration needs to be updated)

Remove `yarn build-preview` (no longer needed after a53a8ef)

---

src/app/pages/FiatOnramp/index.tsx
src/locales/en/translation.json

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1460

Update Transak text

---

src/app/pages/FiatOnramp/index.tsx

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1456
| --- | --- |
| ![localhost_3000_split (4)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/d92e84f1-2e76-48cb-b180-d82f6f932556)  | ![localhost_3000_split (2)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/5efbcb30-6c71-4b29-901a-aa639a6f9c5d)  |
| ![localhost_3000_split](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/0ccdfa7e-8e34-44e4-8c6d-8e61d4978146)  |  ![localhost_3000_split (3)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/12d3de56-22d9-4686-9d56-10c861a96b72) |
cc @donouwens

Restyle Transak: put warning and widget into its own Box

---

playwright/tests/syncTabs.spec.ts
src/app/components/Toolbar/Features/AccountSelector/__tests__/Account.test.tsx
src/app/components/Toolbar/Features/AccountSelector/__tests__/index.test.tsx
src/app/components/Toolbar/Features/AccountSelector/index.tsx
src/app/lib/getAccountBalanceWithFallback.ts
src/app/lib/helpers.ts
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
src/app/state/account/saga.ts
src/app/state/account/types.ts
src/app/state/importaccounts/saga.test.ts
src/app/state/importaccounts/saga.ts
src/app/state/importaccounts/types.ts
src/app/state/transaction/saga.ts
src/app/state/wallet/saga.test.ts
src/app/state/wallet/saga.ts
src/app/state/wallet/types.ts
src/vendors/__tests__/__snapshots__/monitor.test.ts.snap
src/vendors/__tests__/__snapshots__/oasisscan.test.ts.snap
src/vendors/explorer/models/AccountsRow.ts
src/vendors/explorer/swagger.yml
src/vendors/monitor.ts
src/vendors/oasisscan.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1110

Show total balance in account selector

---

src/app/components/BuildBanner/index.tsx
src/config.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1459
To preview this, you can add currently-published-extension's public key to manifest.json:
```json
"key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAybK17ag+0PwHWbYEE36o+SmN35mcXj3RoM8ZBIlOjetdV3uqG8vdzv0YZ2Td21Y0il+1IKt/d9kslRT67C/S2fZ3XKAf96o+j+9/mgdOBwkL7m8XeALzBCYI3sSPnHf36iZu0w9FM9enUFHmq4HPNsT7BqTTEkdtDRRU4JHb+GGLjWvpyB1WIuv7UIJu64zUcZXsGVWZojRG2eISBJZxaItTuFS1210PebsS85++eeHLPWwMMp7d3UXOZpDYoyS07orZJd4c54hZaMNCKKZ5zbupwEuDvSANvEiuxpXe+hHLRnxOlpmhnj+XqkMBTgTFC57b75vhnvOCNbZ/ylW9xwIDAQAB"
```
then remove dev extension and reinstall build-dev extension

Hide banner in published extension

---

.mega-linter.yml
internals/jest/setupTests.ts
package.json
yarn.lock

Due to Mega-Linter updates CI checks are failing 
(sample https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/5665367780/job/15350083731?pr=1553) due to:
- trufflehog errors related to https://github.com/oxsecurity/megalinter/issues/2834
- grype errors https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.grype.yaml#L16
| package  | fix |
| ------------- | ------------- |
| node-fetch  | remove portable-fetch as fetch is part of Node 18 if this is wrong we can use the latest node-fetch if needed |
| minimist  | 1.2.5 -> 1.2.6 https://github.com/minimistjs/minimist#security  |
| ansi-regex  | 5.0.0 -> 5.0.1 https://github.com/chalk/ansi-regex/releases/tag/v5.0.1  |
| minimatch  | false alarm, clean up lock file only, we are still using 3.1.2  |
| protobufjs  | 7.1.2 -> …

Fix CI errors

---

playwright/tests/fiat.spec.ts

A lot of playwright tests on master are being skipped, and CI doesn't fail
https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/5826329626/job/15800051758#step:10:19
> ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/b20c4358-8970-4e18-a2ab-c421f57f0675)
This has been happening since https://github.com/oasisprotocol/oasis-wallet-web/pull/1570.
Additionally, https://github.com/oasisprotocol/oasis-wallet-web/pull/1583/commits/84b30f3c5270843d525ae8bb83dcea518fe572ad broke a test, and it wasn't caught.
Skipped tests seem to be an upstream issue. Reported to: https://github.com/microsoft/playwright/issues/26435

Avoid playwright's buggy test.fail() skipping tests

---

src/app/state/persist/syncTabs.ts
src/app/state/wallet/index.ts

This fixes flaky e2e test switching account should not sync > persisted.
Requires https://github.com/oasisprotocol/oasis-wallet-web/pull/1596 for tests to pass

Fix actions syncing between tabs before state is synced

---

src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
src/app/state/staking/index.ts
src/app/state/staking/saga.ts
src/vendors/__tests__/__snapshots__/monitor.test.ts.snap
src/vendors/__tests__/__snapshots__/oasisscan.test.ts.snap
src/vendors/monitor.ts
src/vendors/oasisscan.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/pull/1517

Don't shuffle inactive validators to the top

---

src/app/components/ErrorFormatter/index.tsx
src/app/lib/__tests__/ledger.test.ts
src/app/lib/ledger.ts
src/locales/en/translation.json
src/types/errors.ts

This improves the error message for users mixing up multiple ledger devices.
E.g.:
- user has two ledgers with different mnemonics
- imports account1 from ledger1 and saves it
- later
- plugs in ledger2 and tries to transfer from saved account1
- see error:
| --- | --- |
| ![Screenshot from 2023-08-26 00-46-45](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/d70b557b-9e24-4b21-ac2d-b7f6c24abe7e)  | ![Screenshot from 2023-08-26 00-46-50](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/305f7b4e-9557-4a56-873b-e1122c06a696)  |

Before transaction validate if ledger device still derives same account

---

src/app/components/Footer/__tests__/index.test.tsx
src/app/components/Footer/index.tsx
src/app/components/MobileFooterNavigation/__tests__/index.test.tsx
src/app/components/MobileFooterNavigation/index.tsx
src/app/components/Sidebar/__tests__/index.test.tsx
src/app/components/Sidebar/index.tsx
src/app/components/Toolbar/Features/AccountSelector/__tests__/index.test.tsx
src/app/components/Toolbar/Features/AccountSelectorButton/index.tsx
src/app/components/Toolbar/index.tsx
src/app/pages/AccountPage/Features/AccountSummary/index.tsx
src/app/pages/AccountPage/__tests__/index.test.tsx
src/app/pages/AccountPage/index.tsx
src/app/state/selectIsAddressInWallet.ts
src/app/state/selectUnlockedStatus.ts
src/app/state/transaction/saga.test.ts
src/app/state/wallet/index.ts
src/app/state/wallet/saga.test.ts
src/app/state/wallet/selectors.ts
src/app/state/wallet/types.ts

(this is more resilient in case state gets incorrectly modified)

Small refactoring to later support deleting accounts

---

playwright/tests/persist.spec.ts
src/app/components/Persist/DeleteProfileButton.tsx
src/app/components/Persist/EraseProfileButton.tsx
src/app/components/Persist/LoginModalLayout.tsx
src/app/components/Persist/UnlockForm.tsx
src/app/state/persist/index.ts
src/app/state/persist/saga.ts
src/locales/en/translation.json

Redesign deleting profile

---

src/app/components/Toolbar/Features/Account/Account.tsx
src/app/components/Toolbar/Features/Account/ImportableAccount.tsx
src/app/components/Toolbar/Features/Account/ManageableAccount.tsx
src/app/components/Toolbar/Features/Account/__tests__/Account.test.tsx
src/app/components/Toolbar/Features/Contacts/AddContact.tsx
src/app/components/Toolbar/Features/Contacts/ContactAccount.tsx
src/app/components/Toolbar/Features/Contacts/ContactAccountForm.tsx
src/app/components/Toolbar/Features/Contacts/DeleteContact.tsx
src/app/components/Toolbar/Features/Contacts/index.tsx
src/app/components/Toolbar/Features/Contacts/layer.ts
src/app/components/Toolbar/Features/SettingsButton/index.tsx
src/app/pages/AccountPage/Features/SendTransaction/index.tsx
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/state/contacts/index.ts
src/app/state/contacts/selectors.ts
src/app/state/contacts/types.ts
src/app/state/persist/index.ts
src/app/state/persist/saga.ts
src/app/state/persist/syncTabs.ts
src/app/state/persist/types.ts
src/locales/en/translation.json
src/store/reducers.ts
src/types/RootState.ts

The first part of Address Book feature. I will add tests in a next PR (or after the first round of review) . In many places I am not following mockups strictly and I am using existing Grommet components etc.

Address Book 

---

playwright/tests/syncTabs.spec.ts
src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/Contacts/__tests__/index.test.tsx
src/app/components/Toolbar/Features/Contacts/index.tsx
src/app/components/Toolbar/Features/SettingsButton/index.tsx
src/locales/en/translation.json
src/styles/theme/ThemeProvider.tsx

Make Contacts available only when profile exists

---

playwright/tests/refreshing-balance.spec.ts
playwright/utils/mockApi.ts
src/app/pages/AccountPage/index.tsx
src/app/state/wallet/saga.test.ts
src/app/state/wallet/saga.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1465

Fix refreshing balances on Home page after switching network

---

playwright/tests/refreshing-balance.spec.ts
src/app/state/account/saga.ts
src/app/state/wallet/saga.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1673
Fixes making transactions with the refreshed balance and displays new balance in AccountSelector.

Fix continuously refreshing balances in wallet slice

---

src/app/components/ResponsiveLayer/index.tsx
src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/AddContact.test.tsx.snap
src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/ScrollableContainer/index.tsx
src/app/components/Toolbar/Features/layer.ts
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap

https://github.com/oasisprotocol/oasis-wallet-web/issues/1710
- remove fill attr
- workaround for Box overlap issue
- bring back original "scrollable area" height that was added when the first tab was created

Fix layout issues

---

.changelog/1735.bugfix.md
src/app/pages/AccountPage/Features/SendTransaction/index.tsx
src/app/state/persist/syncTabs.ts

Issue1:
- add two contacts with the same name
- select second one
- see address1 in input
Issue2:
- add contacts
- open wallet in new tab
- see zero contacts

Fix contacts

---

.changelog/1741.internal.md
playwright/tests/syncTabs.spec.ts

Test contacts syncing initial state too, not just actions

---

.changelog/1748.internal.md
.github/workflows/ci-lint.yml

Keep CI alive while we do not have Towncrier fork updated
sample issue https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/6692075152/job/18180527014?pr=1747.
See https://github.com/oasisprotocol/oasis-core/pull/5421.

Install setuptools to make Towncrier fork work with Python 3.12

---

.changelog/1752.feature.md
playwright/tests/toolbar.spec.ts
src/app/components/DeleteInputForm/index.tsx
src/app/components/Persist/DeleteProfileButton.tsx
src/app/components/Toolbar/Features/Account/Account.tsx
src/app/components/Toolbar/Features/Account/DeleteAccount.tsx
src/app/components/Toolbar/Features/Account/ManageableAccount.tsx
src/app/components/Toolbar/Features/Account/ManageableAccountDetails.tsx
src/app/components/Toolbar/Features/AccountSelector/index.tsx
src/app/state/wallet/index.ts
src/app/state/wallet/selectors.ts
src/locales/en/translation.json

https://oasisprotocol.clickup.com/t/8692qb6gh 
After discussion with Don:
- We won't have to track previous selected accounts. We will open the first one on the list if needed
- We don't need special modal when user cannot remove an account

Remove Account

---

.changelog/1755.internal.md
playwright/tests/extension.spec.ts
playwright/tests/fiat.spec.ts
playwright/tests/migrating-persisted-state.spec.ts
playwright/tests/paraTimes.spec.ts
playwright/tests/persist.spec.ts
playwright/tests/preventSavingInputsToDisk/chromium.spec.ts
playwright/tests/preventSavingInputsToDisk/firefox.spec.ts
playwright/tests/refreshing-balance.spec.ts
playwright/tests/syncTabs.spec.ts
playwright/tests/toolbar.spec.ts
playwright/tests/validators.spec.ts
playwright/utils/fillPrivateKey.ts
playwright/utils/storage.ts
playwright/utils/test-inputs.ts
src/app/pages/E2EPage/index.tsx
src/app/state/wallet/types.ts
src/utils/__fixtures__/test-inputs.ts
src/utils/__tests__/webextension.test.ts

Includes https://github.com/oasisprotocol/oasis-wallet-web/pull/1756
This somewhat checks if we need a state migration yet, for the current e2e state fixture `privateKeyPersistedState`

E2E test migrating slightly older V1 state to current RootState

---

.changelog/1757.internal.md
yarn.lock

Fixes Parcel not compiling `satisfies` keyword in TypeScript.
If I try to use `satisfies` before:
> Build failed. @parcel/transformer-babel: Unexpected token

Reinstall eslint-config-react-app to bump subdependencies

---

.changelog/1775.internal.md
playwright/tests/fiat.spec.ts

Playwright doesn't skip tests anymore (since https://github.com/oasisprotocol/oasis-wallet-web/pull/1664) so this reverts part of commit 14f52305643d7ab01169a265b9ac7c0c88353de3.

Revert TODOs from "Avoid playwright's buggy test.fail() skipping tests"

---

.changelog/1779.internal.md
src/app/pages/E2EPage/index.tsx

migrating-persisted-state.spec.ts didn't have much time after `goto('/e2e')` to use the globals before useRouteRedirects navigates away and cleans up.

Don't cleanup E2E page globals

---

.changelog/1778.trivial.md
src/app/components/Persist/DeleteProfileButton.tsx
src/app/components/Persist/LoginModalLayout.tsx

| --- | --- |
|  ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/d84886b1-3bec-4f6c-b173-cddbd08e4c9b) |  ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/f738178f-9129-46be-8196-e8ee61ab3770) |
Better matches the migration mocks without much effort
cc @donouwens

Show sidebar behind login modal

---

.changelog/1792.internal.md
internals/getSecurityHeaders.js
playwright/tests/csp-react-error-overlay.spec.ts

Broken since 9c7da1ac4954089abee86f3a4900fb36f0d7401b
Note: react-error-overlay only appears during development, and csp-react-error-overlay.spec.ts doesn't test it on CI. Running it locally detects it as broken tho.

Update react-error-overlay CSP hash

---

.changelog/1805.bugfix.md
src/app/components/Toolbar/Features/LayerContainer/index.tsx

The difference on Ubuntu with scrollbars is: optional scrollbar (15px) + margin (24px + 24px) = 63px
Without scrollbars the whole account address would still fit in one line.
| Before https://github.com/oasisprotocol/oasis-wallet-web/pull/1796 | Now | After |
| --- | --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/49e4fd68-c2c2-4534-a3bb-eac9470cb165) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/ca776953-4b11-48de-9fd7-0d7400d4db69) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (2)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/b54e2052-f372-41 …

Increase desktop profile modal width to match pre #1796 width

---

.changelog/1811.bugfix.md
src/app/components/ResponsiveLayer/index.tsx
src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/AddContact.test.tsx.snap
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
src/styles/main.css

Part of it is related to https://github.com/oasisprotocol/oasis-wallet-web/issues/863 issue with nested layers
| --- | --- |
|  ![Screenshot from 2023-12-19 04-42-24](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/db4f1f84-30c4-4a42-ab43-b72d178b5d60) | ![Screenshot from 2023-12-19 04-41-58](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/bbe63dc7-0482-4e97-80f6-53f66ca12068)  |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension360x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/30c92308-ae0c-41e5-bf16-ccc13c1c37c0) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension360x600) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/aff61e …

Fix hiding body scrollbar in Chrome extension and nested layers

---

.changelog/1812.trivial.md
playwright/tests/extension.spec.ts

It hasn't been testing that mnemonic arrives from state since f2f2c44.

Fix e2e extension test for getting state

---

.changelog/1825.internal.md
src/commonRoutes.tsx

TypeScript's import elision doesn't work with Parcel's dead branch removal.

Fix tree-shaking E2E page in production

---

.changelog/.markdownlint.yml
.changelog/1828.internal.md
.markdownlint.yml

Adds code-completion, at least in vscode. Should this be propagated to everywhere?

Add yaml schema to markdownlint configs

---

.changelog/1852.trivial.md
playwright/tests/toolbar.spec.ts

https://github.com/oasisprotocol/oasis-wallet-web/pull/1850 broke master
Somewhat related to 66cde90085a3b585034077ccaa710c8ca55843b5

Fix playwright tests finding duplicate elements in closing modals

---

.changelog/1860.bugfix.md
src/app/components/Button/index.tsx
src/app/components/FatalErrorHandler/index.tsx
src/locales/en/translation.json

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1853
Don is fine with ext layout variant.

Allow to reload extension from within error modal

---

.changelog/1869.internal.md
playwright/tests/persist.spec.ts
playwright/tests/toolbar.spec.ts
src/app/components/FatalErrorHandler/index.tsx
src/app/components/Persist/DeleteProfileButton.tsx
src/app/components/Persist/UnlockForm.tsx
src/app/components/Toolbar/Features/Profile/index.tsx
src/locales/en/translation.json

| --- | --- |
| ![localhost_3000_ (2)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/bd61b3ed-e50c-4150-8914-c44ccd6ff671) | ![localhost_3000_](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/817a344c-536d-48ae-8be4-d454694a9876) |
| ![localhost_3000_ (3)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/8d8fc3da-c226-4cc6-bc98-ea796ca85b09) | ![localhost_3000_ (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/b2c7191e-5798-496b-80ab-a2208f77bcb9) |
Don agrees

Update profile deletion text

---

.changelog/1902.bugfix.md
src/styles/main.css

Re-fixes https://github.com/oasisprotocol/oasis-wallet-web/pull/1811. That worked in Chrome 120, but is broken again in Chrome 124. It most likely broke in 121 when Chrome "fully supported" the css statement that does not work anymore now. https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
| --- | --- |
| ![Screenshot from 2024-04-24 05-53-01](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/d3a93240-0a48-4991-bcac-3b0e34a2279b)  | ![Screenshot from 2024-04-24 05-53-10](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/e7b98109-3481-4e73-bf2b-98e7bab71ee4)  |

Fix hiding body scrollbar in extension again for Chrome 121 and newer

---

.changelog/1905.bugfix.md
extension/src/popup.html
src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/AddContact.test.tsx.snap
src/styles/theme/ThemeProvider.tsx

| --- | --- |
| ![Screenshot from 2024-04-24 23-15-55](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/9e977a00-9bc9-4f59-8863-cc85c8bff156)  |  ![Screenshot from 2024-04-24 23-15-32](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/c2464b1b-3c1a-430c-beb7-9d59a0508a86) |

Denser tab buttons in settings

---

.changelog/1903.bugfix.md
src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/MobileFooterNavigation/index.tsx
src/app/components/Sidebar/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Sidebar/index.tsx
src/styles/theme/ThemeProvider.tsx

| --- | --- |
|  ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/3d62d5ff-3781-4dc6-bbe4-7fd6c59e4218) |  ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_fiat(extension375x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/00959884-410a-4d91-b26b-73437a4c71ae) |

Add active state to mobile navigation buttons

---

.changelog/1909.bugfix.md
src/app/components/Toolbar/Features/Account/Account.tsx
src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap

Fixes:
> @lubej: Manage wallet(settings) is a bit hidden if you only have 1 wallet, as it is the same color as the account name and account address text.
| --- | --- |
| ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/dfc4ef0e-9972-4cae-b211-005f239bf117) | ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/6a213898-065c-48c4-9644-217ae5b741f8)  |

Make buttons to manage accounts more prominent

---

.changelog/1921.bugfix.md
internals/scripts/changelog.js

The only other idea I had was to use env replacement strings, but valid manifest version has to be in `<number><dot>` format during build time.

Sync extension manifest version during version bump

---

.changelog/1931.trivial.md
src/app/components/ThemeSwitcher/index.tsx
src/locales/en/translation.json
src/styles/theme/ThemeProvider.tsx
src/styles/theme/slice/index.ts
src/styles/theme/slice/selectors.ts
src/styles/theme/utils.ts

https://app.clickup.com/t/8694h237j
- using system theme on init is already implemented
- based on UX requirements PR adds system option to Profile dropdown. This setting is not avail in homepage (theme selector when account is not open) 
Looking at ClickUp not sure we need something more. We can bind listeners to respond to system theme changes, but I personally don't care about such feature.

Enable system option in theme dropdown

---

.changelog/1937.trivial.md
src/app/components/Persist/PersistLoadingGate.tsx
src/app/components/TransactionModal/index.tsx
src/app/components/TransactionTypeFormatter/index.tsx
src/app/pages/AccountPage/index.tsx
src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
src/app/pages/ParaTimesPage/ParaTimeFormFooter/index.tsx

| --- | --- |
|   ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_active-delegations(extension375x600 + scrollbar) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/dffa315a-e4f1-4bbe-8eee-889a50bbb287)     |   ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_active-delegations(extension375x600 + scrollbar)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/1d9bd808-9710-4989-9343-55fb6a51426e)     |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_active-delegations(extension375x600 + scrollbar) (3)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/4877b55b-1d75-4aa5-a092-53de740cf6af) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n …

Fix transaction preview layout in extension and loading text size

---

.changelog/1940.feature.md
android/app/src/main/java/com/oasisprotocol/wallet/MainActivity.java

https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE
switching apps
screenshot taken

Prevent app content from being captured in screenshots or apps view

---

.changelog/1933.feature.md
package.json
src/app/components/Ionic/IonicProvider.tsx
src/app/components/Ionic/hooks/useIonicAppStateChangeListener.tsx
src/app/components/Ionic/hooks/useIonicBackButtonListener.ts
src/ionicConfig.ts

Current behavior of mobile platform(for that matter also web/extensions) does not lock the user profile, when leaving the app. Meaning the app would stay indefinitely unlocked, if user does not explicitly lock the wallet. This PR locks the wallet in 30sec of inactivity - but the implementation is not ideal. As timers get "frozen" when put in background, it uses a check upon activating the app, by comparing the timestamps before it went to sleep. Ideal solution would have a background service, with timer implemented - but would add an overhead of additional capacitor plugin.
In combination with hiding app information upon switching between apps(mobile), should be good enough solution.
For demo purposes, this used 5sec timer(instead of 30sec): …

Lock profile when user leaves app on Ionic platform

---

.changelog/1943.bugfix.md
playwright/tests/migrating-v0-ext-persisted-state.spec.ts
src/app/components/CountdownButton/index.tsx
src/app/components/Persist/MigrateV0StateForm.tsx

[screen-recording.webm](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/bf25e9c8-7798-432b-a8b1-c48b3ca921f8)

Add a delay before user can finish V0 migration to encourage reading

---

.changelog/1941.trivial.md
src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Footer/__tests__/index.test.tsx
src/app/components/Footer/index.tsx
src/locales/en/translation.json

Closes [#1910 ](https://github.com/oasisprotocol/oasis-wallet-web/issues/1910)

Update footer text

---

.changelog/1953.trivial.md
playwright/tests/toolbar.spec.ts
src/app/components/DeleteInputForm/index.tsx
src/app/components/Persist/DeleteProfileButton.tsx
src/app/components/Toolbar/Features/Account/DeleteAccount.tsx
src/locales/de/translation.json
src/locales/en/translation.json
src/locales/sl/translation.json
src/locales/tr/translation.json

Supersedes https://github.com/oasisprotocol/oasis-wallet-web/pull/1951
(didn't update chinese translation https://devblogs.microsoft.com/oldnewthing/20060914-02/?p=29743)

Use bold text instead of quotes around "delete" confirmation keyword

---

.changelog/1957.internal.md
android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/variables.gradle
package.json
yarn.lock

- Gradle Plugin 8.2 is required so minimum Android Studio version is Hedgehog https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility
- Capacitor 6 sets a deployment target of iOS 13 and Android 14 (SDK 34)
APK seems Ok after updates. I am not fully able to test Ledger though. That part was not working for me earlier too (I can select BLE device, but cannot list accounts - shows USB Transport error).

Upgrade Capacitor to v6

---

.changelog/1963.bugfix.md
src/app/state/account/saga.ts

Debonding transactions don't change "available" balance
Part of https://github.com/oasisprotocol/oasis-wallet-web/issues/1942#issuecomment-2138543076

Fix refreshing transactions after making a debonding transaction

---

.changelog/1965.bugfix.md
internals/getSecurityHeaders.js
src/config.ts

Heads up: this changes security headers

Migrate from grpc.oasis.dev to grpc.oasis.io

---

.changelog/1967.bugfix.md
playwright/tests/refreshing-balance.spec.ts
src/app/state/account/saga.ts

For https://github.com/oasisprotocol/oasis-wallet-web/issues/1942

Quick fix for updating transactions list by adding more delay

---

.changelog/1983.bugfix.md
src/app/pages/StakingPage/Features/CommissionBounds/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/StakingPage/Features/CommissionBounds/index.tsx

Closes #1982 
seems related to async data rendering

Fix crash when expanding delegation translated by Google

---

.changelog/1984.internal.md
.eslintrc.js
src/app/components/DateFormatter/index.tsx
src/app/components/ErrorFormatter/index.tsx
src/app/components/ImportAccountsStepFormatter/index.tsx
src/app/components/TimeToEpoch/index.tsx
src/app/components/Transaction/__tests__/index.test.tsx
src/app/pages/ParaTimesPage/TransactionError/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
src/utils/eslint-test-noGoogleTranslateCrashingSyntax.tsx

Related to https://github.com/oasisprotocol/oasis-wallet-web/issues/1982
The reason https://github.com/oasisprotocol/oasis-wallet-web/pull/1983 was needed is:
- `CommissionBounds` returned <>string</>
- `details ? <CommissionBounds /> : <Spinner />` conditionally inserted it

Lint rule to detect broken Google Translate in CommissionBounds

---

.changelog/1985.bugfix.md
src/app/pages/AccountPage/Features/AccountDetails/index.tsx
src/app/pages/AccountPage/Features/StakeSubnavigation/index.tsx
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/AccountPage/__tests__/index.test.tsx
src/app/pages/AccountPage/index.tsx
src/app/pages/StakingPage/Features/DelegationList/ActiveDelegationList.tsx
src/app/pages/StakingPage/Features/DelegationList/DebondingDelegationList.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/ActiveDelegationList.test.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/DebondingDelegationList.test.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorList/__tests__/index.test.tsx
src/app/pages/StakingPage/Features/ValidatorList/index.tsx
src/locales/en/translation.json

Supersedes https://github.com/oasisprotocol/oasis-wallet-web/pull/1946
Fixes part of https://github.com/oasisprotocol/oasis-wallet-web/issues/276

Only show Delegations and Debonding tabs in Stake view

---

.changelog/1987.trivial.md
internals/extractMessages/i18next-scanner.config.js
src/locales/en/translation.json

src/styles/theme/icons/mui-icons/MuiWalletIcon.tsx didn't match `src/app/**/**.{js,jsx,ts,tsx}`

Fix extracting translations from MuiWalletIcon

---

.changelog/1996.trivial.md
src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/AddEscrowForm/__tests__/index.test.tsx
src/app/components/AddEscrowForm/index.tsx
src/app/pages/StakingPage/Features/ValidatorList/ValidatorItem.tsx
src/app/pages/StakingPage/Features/ValidatorList/index.tsx
src/locales/en/translation.json

Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1915
One of Don's ideas is to collapse the account balances summary in staking view. In that scenario this becomes essential

Show available amount next to delegation input

---

.changelog/1998.feature.md
src/app/pages/AccountPage/Features/TransactionHistory/index.tsx

Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/1997
`showPendingSection` was "wrongly" evaluated, as it was changing on account loading state. Introduce new variable, that correctly takes into account initial loading state.
https://www.loom.com/share/cda0241c8eaf4c21b20391aba69d3609

Fix initial load for pending txs on account page

---

.changelog/1979.internal.md
src/vendors/oasisscan.ts

Adds cache for the following 2 endpoints:
- getTransaction (`/chain/transaction/{hash}`)
- getRuntimeTransactionInfo (`/runtime/transaction/info?id={paraTimeId}&hash={hash}`)
As those responses won't change, once indexed, they are cached through the app session(until user closes the wallet).

Add transaction detail API cache

---

.changelog/2000.trivial.md
src/app/lib/transaction.ts

`consensusRuntimeId` name was misleading
`txWrapper` name was slightly misleading, and we already use `rtw` in other code

Rename runtime transaction wrapper variable

---

.changelog/2002.trivial.md
src/app/state/account/saga.ts

https://github.com/oasisprotocol/oasis-wallet-web/pull/1954 added nonce field to account and we can use it as another source for updating balance/transactions. This also fixes https://github.com/oasisprotocol/oasis-wallet-web/pull/1954#discussion_r1657332239 and updating transactions list if tx fails and doesn't update balance

Check account nonce when continuously refreshing balance

---

.changelog/2006.trivial.md
src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/AmountFormatter/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/AmountFormatter/index.tsx
src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/ParaTimesPage/TransactionAmount/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
src/styles/main.css

| --- | --- |
| ![wallet dev oasis io_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km](https://github.com/user-attachments/assets/d30cb895-88a3-4370-95de-531a508025c1) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km](https://github.com/user-attachments/assets/7ecf4bd3-a4cb-4ad3-b0d1-ed56a0445d81) |

Use Roboto Mono font for amounts

---

.changelog/2003.trivial.md
src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Transaction/index.tsx

| --- | --- |
| ![wallet dev oasis io_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar)](https://github.com/user-attachments/assets/ba9709d0-3cbb-4a6e-81c5-9d4c3b1d4cc5) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar)](https://github.com/user-attachments/assets/3d03e626-a020-4737-9df9-642f6577ccef) |
| ![wallet dev oasis io_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar) (1)](https://github.com/user-attachments/assets/9e6c02b3-18f4-4a84-afa5-e5bcbc5c7574) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar) (1)](https://github.com/user-attachments/assets/54cc0353-72d5-41a2-9d40-484a92bedbb5)  | …

Change transaction layout to accommodate large numbers in extension

---

.changelog/1944.internal.md
.github/workflows/ci-build.yml
.github/workflows/release.yml
android/app/build.gradle
android/app/src/main/java/org/oasisprotocol/wallet/MainActivity.java
android/app/src/main/res/values/strings.xml
capacitor.config.ts
docs/mobile.md
ios/App/App.xcodeproj/project.pbxproj

Release task has only AAB to avoid confusion what goes to Google app store. Build workflow has both AAB and APK (for testing). Sample fork output  https://github.com/buberdds/oasis-wallet-web/actions/runs/9283327194
Alternative builds samples for future reference:
1. using `android-actions/setup-android@v3` action. Has hardcoded command line tools versions (may be outdated). 
2. manual instalation of Android command line tools. more ugly wokrflow, with hardoded url, but we control everything.
```
- name: Download Command Line Tools
run: |
curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
mkdir -p $HOME/android-sdk/cmdline-tools/latest
unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
mv …
```

Add Android bundle to GitHub Action build artifacts

---

.changelog/2014.bugfix.md
src/app/pages/AccountPage/Features/StakeSubnavigation/index.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap

Suggested by @tjanez 
Partially reverts https://github.com/oasisprotocol/oasis-wallet-web/pull/937
| --- | --- |
| ![Screenshot from 2024-07-18 04-40-22](https://github.com/user-attachments/assets/0ff8ea12-de84-4fed-bba3-8a988ec31854) | ![Screenshot from 2024-07-18 04-40-13](https://github.com/user-attachments/assets/2346f864-6ee1-4826-8d85-2e2dbbe8fcab) |
cc @donouwens

Move staked and debonding count badge into text parentheses

---

.changelog/2016.trivial.md
src/styles/theme/ThemeProvider.tsx

Reimplements #1426
| --- | --- |
| ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes](https://github.com/user-attachments/assets/c779ac31-7e50-4aed-b1a7-c778f68f12d3) | ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90](https://github.com/user-attachments/assets/a0875e06-7564-4df8-bb1b-8a662215db81) |
| ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes (2)](https://github.com/user-attachments/assets/37eda4c8-9a61-4d4f-850f-b06a858c755f) | ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90 (1)](https://github.com/user-attachments/assets/fe2c67a4-2292-4866-8c23-febb42724c32) |

Bring back padding to language and theme dropdowns

---

.changelog/2021.internal.md
towncrier.toml

Assemble changes PRs (https://github.com/oasisprotocol/oasis-wallet-web/pull/2020) should not be blocked by `ci-lint`. Relates to https://github.com/oasisprotocol/oasis-wallet-web/pull/1921

Exclude manifest.json from towncrier check

---

.changelog/2022.bugfix.md
src/app/state/account/saga.ts
src/app/state/account/selectors.test.ts
src/app/state/account/selectors.ts
src/config.ts
src/vendors/__tests__/__snapshots__/oasisscan.test.ts.snap
src/vendors/oasisscan.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/2007

Don't detect pending transactions if no nonce in 20 latest transactions

---

.changelog/2026.bugfix.md
src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Footer/index.tsx
src/locales/en/translation.json
src/locales/fr/translation.json

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/2023
Example of existing translation that was broken:
`"version": "Različica <ReleaseLink/> (<CommitLink/>) zgrajena {{buildTime}}"`
Reverts part of #1941 and #1961.

Fix footer to work with existing translations

---

.changelog/2032.trivial.md
.github/workflows/ci-test.yml

v1 docker-compose got deprecated in ubuntu-latest

Migrate `docker-compose` to `docker compose` to fix cypress e2e

---

.changelog/2029.internal.md
.eslintrc.js
src/app/pages/AccountPage/Features/TransactionHistory/index.tsx
src/utils/eslint-test-noGoogleTranslateCrashingSyntax.tsx
yarn.lock

https://github.com/oasisprotocol/oasis-wallet-web/pull/1954#discussion_r1646806112

Fix noGoogleTranslateCrashingSyntax to use shallow `:has(>...)`

---

.changelog/2031.bugfix.md
src/app/components/AmountFormatter/index.tsx
src/app/pages/StakingPage/Features/DelegationList/DelegationItem.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/index.tsx
src/app/pages/StakingPage/Features/ValidatorList/ValidatorInformations.tsx
src/app/pages/StakingPage/Features/ValidatorList/ValidatorItem.tsx
src/vendors/oasisscan.ts

Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/2030
https://wallet.dev.oasis.io/account/oasis1qprtzrg97jk0wxnqkhxwyzy5qys47r7alvfl3fcg/stake/active-delegations
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5c3b5a04-f560-4fd6-8714-d6c948bd3953) | ![image](https://github.com/user-attachments/assets/e6e90bb0-fa03-404f-b1ce-17911bcfd2f8) |
- Fixes selecting non-validators. Previously all "undefined" validators were pre-expanded and crashed when collapsing + re-expanding their details
- Prints delegation's address
- Round delegation amounts in the table. Accurate delegation amount is still displayed when expanding
- (we currently don't have a rounding indicator like https://github.com/oasisprotocol/explorer/blob/1651e1a64a4ae9a7743b3fdc78 …

Fix display of delegations to non-validators

---

.changelog/2035.bugfix.md
src/app/components/AddressBox/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/AddressBox/index.tsx
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap

Before
https://github.com/user-attachments/assets/32346cb5-ade5-4df4-8ee8-edd298f3e025 
After
https://github.com/user-attachments/assets/73f81a49-84eb-4595-abdc-cc21a5bac8c8

Prevent AddressBox in expanded row from resizing whole validators table

---

.changelog/2061.bugfix.md
src/app/components/TransactionModal/index.tsx
src/app/state/importaccounts/saga.ts
src/app/state/transaction/saga.ts
src/app/state/wallet/index.ts
src/app/state/wallet/saga.ts

Fixes https://github.com/oasisprotocol/wallet/issues/2058
| --- | --- |
| ![wallet dev oasis io_](https://github.com/user-attachments/assets/ec757481-221a-4541-b755-cec4c3033f4b) | ![localhost_3000_](https://github.com/user-attachments/assets/c513c082-fc2b-4c57-8bc2-ccdd534fb23e) |

Prevent importing from mnemonic when offline

---

.changelog/2064.internal.md
src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/TimeToEpoch/__tests__/index.test.tsx
src/app/components/TimeToEpoch/index.tsx
src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/index.test.tsx
src/app/pages/StakingPage/Features/CommissionBounds/__tests__/index.test.tsx
src/app/pages/StakingPage/Features/CommissionBounds/index.tsx
src/app/pages/StakingPage/Features/DelegationList/DebondingDelegationList.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/DebondingDelegationList.test.tsx
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
src/app/pages/StakingPage/Features/DelegationList/index.tsx
src/app/state/network/index.ts
src/app/state/network/saga.test.ts
src/app/state/network/saga.ts
src/app/state/network/types.ts
src/app/state/persist/syncTabs.ts
src/app/state/staking/saga.test.ts
src/app/state/staking/saga.ts
src/utils/__fixtures__/test-inputs.ts

The second part of https://github.com/oasisprotocol/wallet/issues/1991
- For some reason changes triggered ticker updates in snapshots
- `FromMnemonic` not related to changes. PR hits timeouts in CI because component calls `getAccountBalanceWithFallback` saga for each account in modal. It is not needed in this unit tests.

Delay GetEpoch request until needed

---

.changelog/2089.internal.md
playwright/utils/mockApi.ts
src/app/components/Footer/__tests__/index.test.tsx
src/app/pages/AccountPage/__tests__/index.test.tsx
src/types/env.d.ts
src/vendors/backend.ts

Closes https://github.com/oasisprotocol/wallet/issues/2079
One snapshot will need to be updated when `REACT_APP_BACKEND` changes, but that is intentional
```
-           Oasis Scan API & Oasis gRPC
+           Nexus API & Oasis gRPC
```

Override API in e2e tests to allow quick backend switch

---

.changelog/2110.bugfix.md
android/variables.gradle

Mitigates StrandHogg attack, due to vulnerability on Android 10 or lower.
https://developer.android.com/privacy-and-security/risks/strandhogg#mitigations

android: Bump min SDK version

---

.changelog/2118.internal.md
extension/src/ExtLedgerAccessPopup/ExtLedgerAccessPopup.tsx
extension/src/ExtLedgerAccessPopup/__tests__/__snapshots__/index.test.tsx.snap
extension/src/ExtLedgerAccessPopup/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
src/app/pages/OpenWalletPage/FromLedgerWebExtension.tsx
src/app/useRouteRedirects.tsx
src/locales/en/translation.json

Supersedes https://github.com/oasisprotocol/wallet/pull/2094
---
Extracted from https://github.com/oasisprotocol/wallet/pull/2084
Related to https://github.com/oasisprotocol/wallet/pull/2084#discussion_r1830380814
Previous flow:
- '#/open-wallet/ledger' has "Grant access to your Ledger" button
- it opens '#/open-wallet/connect-device' in permanent popup as well as navigates self-closing popup to '#/open-wallet/ledger/usb' (both stay open)
- connect-device popup has "Connect Ledger device" button that requests usb permission, selects device, and triggers listing accounts in redux. That is synced into self-closing popup
- when done in connect-device popup, user tries to continue in self-closing popup, but it closes
- when reopening, and navigating to import from ledger again, it skips some …

Refactor how extension requests ledger access (don't rely on state sync) and close popup

---

.changelog/2119.process.md
extension/src/ExtLedgerAccessPopup/ExtLedgerAccessPopup.tsx
internals/extractMessages/i18next-scanner.config.js
package.json
playwright/tests/extension.spec.ts
playwright/tests/syncTabs.spec.ts
src/app/components/Toolbar/Features/Contacts/AddContact.tsx
src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
src/app/components/Toolbar/Features/Contacts/__tests__/index.test.tsx
src/app/pages/OpenWalletPage/Features/FromBleLedger/index.tsx
src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx
src/app/pages/ParaTimesPage/getParaTimeName.ts
src/locales/en/translation.json

Built on top of https://github.com/oasisprotocol/wallet/pull/2118
Fixes 0032df53aec9838d2aac7804d10c475e83e8beb9

Fix extracting translations

---

.changelog/2126.internal.md
playwright/tests/extension.spec.ts
playwright/tests/fiat.spec.ts

CI on all pullrequests was failing because transak introduced at least 3 new errors

Temporarily ignore transak console errors in E2E tests

---

.changelog/2132.trivial.md
playwright/tests/extension.spec.ts

Looks like extensions don't send origin/referrer header when loading iframe and transak now responds with `Referrer-Policy: same-origin; X-Frame-Options: sameorigin;`
Luckily our extension does not embed transak, but opens it in a new tab. Mobile app too, except maybe on tablets. Not sure if iframe would load in a mobile app context

Disable E2E test for transak embedded in extension

---

.changelog/2130.trivial.md
playwright/tests/syncTabs.spec.ts
playwright/utils/mockApi.ts

Fixes `yarn test:screenshots`, broken since d3d1af0.
Screenshots failing in monthly CI: https://github.com/oasisprotocol/wallet/actions/runs/13598927233/job/38021610407

Fix Nexus API mocked data to fix making screenshots

---

.changelog/2154.bugfix.md
playwright/tests/extension.spec.ts
playwright/tests/fiat.spec.ts
src/app/pages/FiatOnrampPage/index.tsx

Related to https://github.com/oasisprotocol/wallet/pull/2132
Extensions don't send origin/referrer header when loading iframe and transak now
responds with `Referrer-Policy: same-origin; X-Frame-Options: sameorigin;`.
We embed transak based on window size, so transak could get embedded and fail if
user opens the extension in a large tab. This mitigates a failure in 5 seconds.

Fallback to transak button if embedded doesn't initialize after 5sec

---

.changelog/2169.trivial.md
playwright/tests/syncTabs.spec.ts

This test usually passes after two automatic retries. And very rarely it fails all three repeats
Tried to reproduce here:
https://github.com/oasisprotocol/wallet/actions/runs/14473819140/job/40594465703 0/3 failed
https://github.com/oasisprotocol/wallet/actions/runs/14473819140/job/40597292495 7/9 failed
After
https://github.com/oasisprotocol/wallet/actions/runs/14473822355/job/40594471812 0/3 failed
https://github.com/oasisprotocol/wallet/actions/runs/14473822355/job/40597299796 0/3 failed
https://github.com/oasisprotocol/wallet/actions/runs/14473822355/job/40598095792 0/3 failed

Fix flaky test - sync 44 accounts in 10 tabs

---

.changelog/2170.internal.md
src/styles/theme/ThemeProvider.tsx

- improves scrollbar color
- supports `@media (prefers-color-scheme: dark)` in svg icons
| --- | --- |
| ![before1](https://github.com/user-attachments/assets/31d90638-a41b-4f54-a4c6-a41f469a5e4b) | ![after1](https://github.com/user-attachments/assets/d8c5c069-4821-4b55-9d45-c75e8821f725) |
| ![before4](https://github.com/user-attachments/assets/75ece158-a22c-45b0-8639-39d0a919621f) | ![after4](https://github.com/user-attachments/assets/b9a89d9a-ab69-46f0-97d1-00e9de6efdf4) |
| ![before3](https://github.com/user-attachments/assets/e502ac13-9849-4797-aa42-5421afaf34ad) | ![after3](https://github.com/user-attachments/assets/5e3fb8d2-b832-454d-a518-9ebc1dd34872) |
| ![before2](https://github.com/user-attachments/assets/1894a021-950a-458f-b2be-f43c248afd63) | …

Set CSS color-scheme to match grommet dark theme
