oasisprotocol/wallet

- docker-compose.yml
- docker/oasis-explorer/Dockerfile
- docker/oasis-node/Dockerfile
> chore: use fqdn for docker registries

- src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddEscrowForm/index.tsx
- src/app/pages/AccountPage/Features/SendTransaction/index.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/187
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/186
> Fix input validation in AddEscrowForm and SendTransaction

- cypress/fixtures/account.ts
- src/app/components/PrettyAddress/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/PrettyAddress/__tests__/index.test.tsx
- src/app/components/PrettyAddress/index.tsx
- src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/index.test.tsx
- src/app/pages/StakingPage/Features/DelegationList/__tests__/ActiveDelegationList.test.tsx
- src/app/pages/StakingPage/Features/DelegationList/__tests__/DebondingDelegationList.test.tsx
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/index.test.tsx
> chore: improve bech32 validation in PrettyAddress

- src/app/pages/StakingPage/Features/ValidatorMediaInfo/__tests__/index.test.tsx
- src/app/pages/StakingPage/Features/ValidatorMediaInfo/index.tsx
> fix: reject dangerous email payloads

- public/index.html
- public/manifest.json
Related https://github.com/oasisprotocol/oasis-wallet-web/issues/266
> Update app title and description

- src/app/pages/CreateWalletPage/index.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/274
> Blur mnemonic using filter (Firefox doesn't support backdropFilter)

- src/app/components/TransactionModal/index.tsx
- src/app/components/TransactionPreview/index.tsx
- src/locales/en/translation.json
- src/locales/fr/translation.json
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/409.
> Remove Balance field from Preview transaction dialog

- src/app/components/Transaction/InfoBox.tsx
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Transaction/__tests__/index.test.tsx
- src/app/components/Transaction/index.tsx
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/275.
> Use default cursor on Amount and Block panes

- src/app/state/wallet/saga.test.ts
- src/app/state/wallet/saga.ts
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/267.
> Account switching issue - wrong account's details are displayed

- README.md
- src/app/components/FatalErrorHandler/index.tsx
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Transaction/__tests__/index.test.tsx
- src/app/components/Transaction/index.tsx
- src/locales/en/translation.json
- src/vendors/explorer/runtime.ts
- a new codepath for #411. no automated tests. missing french translation
- failed block explorer requests were unhelpfully showing up as "undefined," an improvement to that
fixes #411
part of #403
> non-major features

- src/app/state/staking/saga.ts
Fixes code style change in https://github.com/oasisprotocol/oasis-wallet-web/pull/435
> Fix code style

- src/app/pages/AccountPage/Features/TransactionHistory/index.tsx
- src/app/pages/AccountPage/index.tsx
- src/app/pages/StakingPage/Features/ValidatorList/index.tsx
- src/app/state/account/index.ts
- src/app/state/account/saga.ts
- src/app/state/account/selectors.ts
- src/app/state/account/types.ts
- src/app/state/staking/index.ts
- src/app/state/staking/saga.ts
- src/app/state/staking/selectors.ts
- src/app/state/staking/types.ts
- src/locales/en/translation.json
- src/vendors/explorer/README.md
- src/vendors/explorer/apis/AccountsApi.ts
> non-fatal explorer interaction: validators, account, transactions

- README.md
As per https://oasis-labs.slack.com/archives/CHTNKCRL0/p1637720075217500?thread_ts=1637719773.217400&cid=CHTNKCRL0
> Update README to reflect support for mainnet

- src/app/pages/StakingPage/Features/DelegationList/__tests__/ActiveDelegationList.test.tsx
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
Reproduces https://github.com/oasisprotocol/oasis-wallet-web/issues/436
> Reproduce rounding issue with 7% validator fee

- src/app/pages/CreateWalletPage/__tests__/index.test.tsx
- src/app/pages/CreateWalletPage/slice/index.ts
This is never expected to fail
> Check that HDKey.generateMnemonic is bip39 valid

- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/app/pages/StakingPage/Features/ValidatorList/index.tsx
Fixes sorting by name on the validator list page. If validator name is not present, sort by oasis address.
> StakingPage: Support sorting by validator name

- src/app/pages/StakingPage/Features/ValidatorList/index.tsx
- src/app/pages/StakingPage/Features/ValidatorMediaInfo/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorMediaInfo/index.tsx
- src/app/state/staking/types.ts
- src/styles/main.css
> StakingPage: Add support for validator icon (move from #298)

- README.md
- docker/oasis-node/README.md
- internals/serve-with-csp.json
- package.json
- src/app/components/ErrorFormatter/index.tsx
- src/app/components/ReclaimEscrowForm/index.tsx
- src/app/components/Transaction/index.tsx
- src/app/components/TransactionModal/index.tsx
- src/app/pages/StakingPage/Features/ValidatorList/ValidatorInformations.tsx
- src/app/state/wallet/saga.ts
- src/locales/en/translation.json
Related to https://github.com/oasisprotocol/oasis-wallet-web/issues/204
> Add content-security-policy to `start:prod`

- src/app/pages/OpenWalletPage/index.tsx
> OpenWalletPage: Add notification for BitPie wallet users

- src/app/components/MnemonicGrid/index.tsx
- src/app/components/MnemonicValidation/index.tsx
- src/app/components/NoTranslate/index.tsx
- src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/CreateWalletPage/index.tsx
- src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
Fixes half of https://github.com/oasisprotocol/oasis-wallet-web/issues/521
> Disable Google Translate on mnemonic

- src/app/components/ErrorFormatter/index.tsx
- src/locales/en/translation.json
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/374
Improves https://github.com/oasisprotocol/oasis-wallet-web/issues/376
Not sure what to do about translations :shrug:
> Explain ledger errors

- src/app/components/ErrorFormatter/index.tsx
- src/app/components/FatalErrorHandler/index.tsx
- src/app/components/TransactionPreview/index.tsx
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/app/pages/AccountPage/Features/TransactionHistory/index.tsx
- src/app/pages/OpenWalletPage/index.tsx
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/app/pages/StakingPage/Features/ValidatorList/ValidatorInformations.tsx
- src/locales/en/translation.json
This PR fixes smaller inconsistencies and stylistic errors (missing full-stop, capitalized word for no reason outside of title, redundant adjectives and spaces) so the original English translation file can serve as a solid base for future translations.
> i18n: Smaller fixes to original phrases

- src/locales/fr/translation.json
This PR syncs French translation with upstream and also fixes some typos.
Kudos to Raphael Marc Landers :wink:
> i18n: Sync French translation

- src/app/lib/helpers.test.ts
- src/app/lib/helpers.ts
- src/app/state/transaction/saga.ts
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/533.
> Not possible to send certain fractional amounts of tokens

- src/app/components/Sidebar/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Sidebar/index.tsx
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/locales/en/translation.json
Some users have been confused when they don't see buttons to transfer when "opening" a wallet by URL, e.g.
https://wallet.oasisprotocol.org/account/oasis1qrh9yz4nwsngkj5w9w6hktn4rca8ycwm0gw8v2zy
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3758846/148590618-8c8c1064-c132-48fa-9e80-7c937746e2fd.png) | ![image](https://user-images.githubusercontent.com/3758846/148590671-e78100e9-06ad-4cb2-9642-bcfc3bda4bd2.png) |
> Show a warning banner when no wallet is open

- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/app/pages/StakingPage/Features/ValidatorList/index.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/569
| --- | --- |
| ![localhost_3000_account_oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm_stake](https://user-images.githubusercontent.com/3758846/148620243-dd93c15f-159d-44a4-81e8-c541f5f0d371.png)  | ![localhost_3000_account_oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm_stake (1)](https://user-images.githubusercontent.com/3758846/148620244-acb318fb-9e67-439f-8cf0-345462711bf8.png)  |
> Remove default oasis logo from validators without logo

- src/app/lib/ledger.ts
- src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/index.test.tsx
- src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
- src/app/pages/OpenWalletPage/index.tsx
- src/app/state/ledger/saga.ts
- src/locales/en/translation.json
- yarn.lock
Related to https://github.com/oasisprotocol/oasis-wallet-ext/pull/248
> Show instructions before opening wallet from Ledger

- src/app/pages/AccountPage/index.tsx
- src/app/pages/StakingPage/Features/DelegationList/__tests__/ActiveDelegationList.test.tsx
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/app/pages/StakingPage/Features/ValidatorList/ValidatorInformations.tsx
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/index.test.tsx
- src/app/pages/StakingPage/Features/ValidatorList/index.tsx
- src/app/state/account/index.ts
- src/app/state/account/saga.ts
- src/app/state/account/types.ts
- src/app/state/network/saga.ts
- src/app/state/staking/saga.test.ts
- src/app/state/staking/saga.ts
- src/app/state/staking/types.ts
- src/vendors/__snapshots__/monitor.spec.ts.snap
- src/vendors/explorer/README.md
- src/vendors/explorer/models/AccountsRow.ts
- src/vendors/explorer/models/ValidatorRow.ts
- src/vendors/explorer/swagger.yml
- src/vendors/monitor.spec.ts
- src/vendors/monitor.ts
Towards https://github.com/oasisprotocol/oasis-wallet-web/issues/693
cc @buberdds (can't set as reviewer)
> Refactor backend (step towards supporting oasisscan backend)

- src/app/components/FatalErrorHandler/index.tsx
- src/locales/en/translation.json
- src/locales/fr/translation.json
Switch to new Support ticketing system
> Update Fatal Error message

- src/app/lib/helpers.ts
- src/app/state/account/saga.ts
- src/app/state/wallet/saga.ts
May reduce panic in users who saw `Total balance: 0` when API is broken
> Fallback to RPC if get account fails

- src/app/components/FatalErrorHandler/index.tsx
- src/app/components/TransactionModal/index.tsx
- src/app/components/TransactionStatus/index.tsx
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/CreateWalletPage/__tests__/index.test.tsx
- src/app/pages/CreateWalletPage/index.tsx
- src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
- src/styles/theme/ThemeProvider.tsx
Add missing `dark` boolean prop to handle light theme styles correctly.
vs
> Fix modal light theme styles

- src/index.tsx
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/777
> Remove unused HMR code

- src/app/state/staking/saga.test.ts
- src/app/state/staking/saga.ts
- src/vendors/__tests__/__snapshots__/monitor.spec.ts.snap
- src/vendors/__tests__/__snapshots__/oasisscan.spec.ts.snap
- src/vendors/__tests__/monitor.spec.ts
- src/vendors/__tests__/oasisscan.spec.ts
- src/vendors/monitor.ts
- src/vendors/oasisscan.ts
Extends https://github.com/oasisprotocol/oasis-wallet-web/pull/704
> Replace RPC delegations with oasisscan API

- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/NetworkDowntimeNotification/index.tsx
- src/app/index.tsx
- src/locales/en/translation.json
- src/locales/fr/translation.json
will open revert PR on 11th Apr
> Network downtime notification banner

- src/app/components/NetworkDowntimeNotification/index.tsx
- src/locales/en/translation.json
- src/locales/fr/translation.json
> Update downtime notice

- internals/extractMessages/i18next-scanner.config.js
- src/app/components/Sidebar/index.tsx
- src/locales/i18n.ts
- src/locales/sl/translation.json
Adds Slovenian translation of the Oasis Wallet.
> i18n: Add Slovenian translation

- internals/extractMessages/i18next-scanner.config.js
- src/app/components/Sidebar/index.tsx
- src/locales/i18n.ts
- src/locales/tr/translation.json
Superseeds https://github.com/oasisprotocol/oasis-wallet-web/pull/292
> i18n: Add Turkish translation

- .github/workflows/mega-linter.yml
- internals/extractMessages/i18next-scanner.config.js
- src/app/components/ErrorFormatter/index.tsx
- src/app/components/FatalErrorHandler/index.tsx
- src/app/components/Footer/index.tsx
- src/app/components/Sidebar/index.tsx
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/app/pages/AccountPage/Features/SendTransaction/index.tsx
- src/app/pages/HomePage/index.tsx
- src/locales/en/translation.json
This PR adds a check to CI that all terms in source files are also present in the original English translation file which is a baseline for Transifex.
Developers should always run `yarn extract-messages`, if they changed any terms in the source code to also update the English translation file. Synchronizing other translations is done by Transifex which fetches any English updates and applies them to other languages.
Other changes:
- enables sorting of all terms in translation files to assure canonical form among i18next-scaner versions and source code refactorings in the future
- adds missing defaults for all terms in the source code
> CI: Require English translation file in sync with source code

- src/app/components/FatalErrorHandler/index.tsx
- src/app/components/Toolbar/Features/AccountSelector/index.tsx
- src/app/components/TransactionStatus/index.tsx
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/app/pages/AccountPage/Features/SendTransaction/index.tsx
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/app/pages/StakingPage/Features/ValidatorList/ValidatorInformations.tsx
- src/locales/en/translation.json
Followup to #541. Fixes inconsistencies among few terms.
Related #810 .
> i18n: Regression fix for source translations

- package.json
- src/app/lib/ledger.test.ts
- src/app/lib/ledger.ts
- src/utils/@oasisprotocol/ledger.d.ts
- yarn.lock
Requires https://github.com/oasisprotocol/oasis-wallet-web/pull/825
> Upgrade @oasisprotocol/ledger and use it's new type declaration

- src/app/state/wallet/saga.test.ts
- src/store/__tests__/reducer.test.ts
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/800
> Fix warnings in tests

- internals/getCsp.js
- internals/prod-scripts.js
```diff
- ... https://monitor.oasis.dev  ;  img-src 'self' data: https:;
+ ... https://monitor.oasis.dev; img-src 'self' data: https:;
```
> Remove empty lines and spaces from CSP

- README.md
- internals/extractMessages/i18next-scanner.config.js
- src/app/components/Sidebar/index.tsx
- src/locales/i18n.ts
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/810#issuecomment-1102828734
> Describe how translations are synced in README

- .gitattributes
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
> be ignored for the repository's language statistics and hidden by default in diffs
> Mark auto-generated files

- src/app/components/FatalErrorHandler/index.tsx
- src/app/components/Modal/index.tsx
- src/app/components/TransactionModal/index.tsx
- src/app/pages/AccountPage/index.tsx
- src/app/pages/CreateWalletPage/index.tsx
- src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
- Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/863
- Makes code around Layers more consistent: escape to close, override background color, and explicitly uses `modal` everywhere
> Fix keyboard accessibility after creating a wallet

- src/app/components/Sidebar/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Sidebar/index.tsx
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/903#issuecomment-1180793892
> Restyle Github sidebar link from green to white

- src/app/components/AddressBox/index.tsx
- src/app/components/AmountFormatter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AmountFormatter/__tests__/index.test.tsx
- src/app/components/AmountFormatter/index.tsx
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
- src/locales/en/translation.json
PR updates Account Summary section only. Make Account Summary more readable on mobile. Should work better with larger Rose amounts. General account notices moved to the top of container.
current mobile
updated mobile/extension
This will affect large screen view
> Change UI to be more similar to current extension: Account Summary

- src/app/components/Sidebar/index.tsx
- src/app/components/Toolbar/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/AccountPage/index.tsx
Follows #937 
- bring back z-index value 
- set width (when counter was equal to 1, counter bubble did not look good)
> Fix mobile z-index values

- src/app/components/AmountFormatter/index.tsx
- src/app/components/DateFormatter/__tests__/index.test.tsx
- src/app/components/DateFormatter/index.tsx
- src/app/components/ShortAddress/__tests__/index.test.tsx
- src/app/components/ShortAddress/index.tsx
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/index.test.tsx
- src/app/components/Transaction/InfoBox.tsx
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Transaction/__tests__/index.test.tsx
- src/app/components/Transaction/index.tsx
- src/app/pages/AccountPage/Features/TransactionHistory/index.tsx
- src/locales/en/translation.json
- src/styles/theme/ThemeProvider.tsx
> Change UI to be more similar to current extension: Transactions List

- src/app/components/Transaction/InfoBox.tsx
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
Follows https://github.com/oasisprotocol/oasis-wallet-web/pull/938
> Transaction List: restore box-shadow to improve keyboard accessibility

- src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ReclaimEscrowForm/__tests__/index.test.tsx
- src/app/components/ReclaimEscrowForm/index.tsx
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/locales/en/translation.json
Fixes part of https://github.com/oasisprotocol/oasis-wallet-web/issues/492
> Add "Reclaim all" button

- src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddEscrowForm/index.tsx
- src/app/components/FatalErrorHandler/index.tsx
- src/app/components/MnemonicValidation/index.tsx
- src/app/components/Modal/index.tsx
- src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ReclaimEscrowForm/index.tsx
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/index.tsx
- src/app/components/TransactionModal/index.tsx
- src/app/pages/AccountPage/Features/SendTransaction/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/CreateWalletPage/index.tsx
- src/app/pages/HomePage/index.tsx
- src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
- src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx
- src/app/pages/OpenWalletPage/index.tsx
- src/styles/theme/ThemeProvider.tsx
Apparently all non-icon-buttons had customized `style={{ borderRadius: '4px' }}`
> Change button border-radius in theme

- src/app/components/ResponsiveGridRow/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ResponsiveGridRow/__tests__/index.test.tsx
- src/app/components/ResponsiveGridRow/index.tsx
- src/app/components/TransactionTypeFormatter/index.tsx
https://github.com/oasisprotocol/oasis-wallet-web/issues/951
> Fix transaction preview formatting

- src/app/components/DateFormatter/index.tsx
- src/app/components/Footer/index.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/948
> Use en-US locale in tests

- .eslintrc.js
- internals/scripts/dump_validators.ts
- src/app/lib/helpers.test.ts
- src/app/lib/helpers.ts
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/945
> Make row keys unique in debonding list

- src/app/components/AmountFormatter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AmountFormatter/index.tsx
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/966
| --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km](https://user-images.githubusercontent.com/3758846/184996059-226debae-cd7f-48ca-81d3-899d1a7d2d3d.png)  |  ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (1)](https://user-images.githubusercontent.com/3758846/184996068-191c48ab-8d39-4b81-80ae-8003acb105a9.png) |
> Wrap AmountFormatter with span element

- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
- src/app/state/network/saga.ts
- src/config.ts
Before: 78+64+740+75 ms
After: 612 ms
> Speedup loading network configuration

- src/app/state/wallet/saga.test.ts
- src/app/state/wallet/saga.ts
Select the first wallet from a selection after all wallets are loaded
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/934
> Fix importing multiple accounts from ledger

- src/styles/theme/icons/language/Language.tsx
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/999#discussion_r972176187
> Link to docusaurus source from language icon

- cypress/integration/open-wallet.ts
- src/app/lib/key.ts
> Detect invalid private keys when importing them

- cypress/integration/open-wallet.ts
- src/app/state/wallet/index.ts
- src/app/state/wallet/saga.test.ts
- src/app/state/wallet/saga.ts
Fixes https://github.com/oasisprotocol/oasis-wallet-web/pull/980#issuecomment-1238192565
> Fix importing and reselecting the same account and cleanup

- cypress/integration/open-wallet.ts
- cypress/integration/scenario-account-switcher.ts
- cypress/integration/scenario-transaction.ts
- src/app/components/PasswordField/index.tsx
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx
Just making it reusable for persisted state
> Extract PasswordField from FromPrivateKey

- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/locales/en/translation.json
On Testnet, say:
> To send, receive, stake and swap TEST tokens, open your wallet!
> Mention the correct ticker in account summary

- src/locales/sl/translation.json
Includes latest ParaTime terms for deposits/withdrawals and some other minor fixes.
> i18n: Update Slovenian translation

- src/app/pages/AccountPage/index.tsx
Fixes #940.
It doesn't redirect (as suggested in the issue), just indicate the problem and avoids the crash.
> Handle invalid address in url

- src/app/components/MnemonicValidation/index.tsx
- src/app/pages/AccountPage/Features/SendTransaction/index.tsx
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx
Part of oasisprotocol/oasis-wallet-web#1064
> fix 1064: submit forms not just on submit button click

- renovate.json
I'm bothered by "chore(deps): update tests" PR names :D
> Rename renovate group PRs

- src/styles/theme/ThemeProvider.tsx
| --- | --- |
| ![](https://user-images.githubusercontent.com/3758846/197801236-e87f8890-0c03-4c42-9558-0fa35a52c755.png) ![](https://user-images.githubusercontent.com/3758846/197801232-6f06f70c-3042-462d-9e8b-d96c012cc598.png)  | ![b](https://user-images.githubusercontent.com/3758846/197801223-06209a60-24a2-43eb-b78e-390f23fbd55e.png) ![c](https://user-images.githubusercontent.com/3758846/197801215-2eea6ce3-7edf-4795-9c35-8eb3558f13a9.png) |
| ![](https://user-images.githubusercontent.com/3758846/197801239-ef310d4d-daa8-4627-a5e6-12877b9e0bf6.png) ![](https://user-images.githubusercontent.com/3758846/197801226-13dfdc4f-4332-4d3d-b724-14aef8cdf7e7.png) | ![](https://user-images.githubusercontent.com/3758846/197801211-c450a69b-9e87-4573-8656-5608a6724c3f.png) …
> Restyle default tooltips and toast notifications

- src/app/pages/ParaTimesPage/ParaTimeContent/__tests__/index.test.tsx
- src/app/pages/ParaTimesPage/ParaTimeContent/index.tsx
- src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/__tests__/index.test.tsx
- src/app/pages/ParaTimesPage/TransactionAmount/__tests__/index.test.tsx
- src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/index.test.tsx
- src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/index.test.tsx
- src/app/pages/ParaTimesPage/__tests__/index.test.tsx
Fill gaps in test coverage around ParaTimes components.
> ParaTimes: increase test coverage around components

- package.json
- yarn.lock
Added by parcel auto loader when running yarn start after parcel 2.8.0 update
> Add string_decoder to deps after Parcel update

- playwright/tests/extension.spec.ts
Part of https://github.com/oasisprotocol/oasis-wallet-web/issues/1061
> Playwright E2E test extension popup gets state from background page

- src/app/components/Header/index.tsx
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1124
| --- | --- |
| ![1a](https://user-images.githubusercontent.com/3758846/201237222-8839d5eb-9773-4c17-b775-6c988ec653ab.png)  |  ![2a](https://user-images.githubusercontent.com/3758846/201237227-991003d8-3012-417c-8be1-503ae57d2467.png) |
| ![1b](https://user-images.githubusercontent.com/3758846/201237224-802577dd-e8db-4c21-bb7f-43b0a1aede97.png)  | ![2b](https://user-images.githubusercontent.com/3758846/201237229-5afc55bc-7149-4e9e-939b-baa8824c75ea.png) |
> Change layout of pagination for account import

- src/app/components/AddressBox/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/PrettyAddress/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/PrettyAddress/index.tsx
- src/app/components/ShortAddress/index.tsx
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
> Disable google translate on displayed account addresses

- src/app/pages/StakingPage/Features/CommissionBounds/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/CommissionBounds/index.tsx
> Split commission bound entries into rows

- cypress/e2e/create-wallet.cy.ts
- cypress/e2e/open-wallet.cy.ts
- cypress/e2e/scenario-account-switcher.cy.ts
- cypress/e2e/scenario-transaction.cy.ts
- src/app/components/MnemonicField/index.tsx
- src/app/components/MnemonicValidation/index.tsx
- src/app/components/PasswordField/index.tsx
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/index.tsx
- src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/index.tsx
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
- src/app/pages/ParaTimesPage/TransactionRecipient/index.tsx
Mostly extracted from https://github.com/oasisprotocol/oasis-wallet-web/pull/975
> Refactor inputs

- src/app/components/Toolbar/Features/AccountSelector/__tests__/Account.test.tsx
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/index.tsx
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
Broken since I rebased https://github.com/oasisprotocol/oasis-wallet-web/pull/990 over https://github.com/oasisprotocol/oasis-wallet-web/pull/1124/commits/3255d9b1c462c958ba3940c7f56023e18bf32967: it started displaying 0', 1', .. as account numbers
> Fix displayAccountNumber

- .gitignore
Ignore autogenerated `.idea` folder that JetBrains tool generate.
> Add JetBrains tools to git ignore

- docker-compose-testnet.yml
- docker-compose.yml
New versions are located in clickhouse/clickhouse-server only.
> Change ClickHouse Docker repository.

- internals/getBuildData.js
- src/app/components/Footer/index.tsx
Related to https://github.com/oasisprotocol/oasis-wallet-web/issues/1118
| --- | --- |
| on a tagged commit: |  |
| "Version: [1.0.0-dev.1](https://github.com/oasisprotocol/oasis-wallet-web/releases/tag/v1.0.0-dev.1) (commit: [sha0000](https://github.com/oasisprotocol/oasis-wallet-web/commit/sha0000000000000000000000000000000000000)) built at 1/1/1970, 1:00:00 AM"  | "Version: [1.0.0-dev.1](https://github.com/oasisprotocol/oasis-wallet-web/releases/tag/v1.0.0-dev.1) (commit: [sha0000](https://github.com/oasisprotocol/oasis-wallet-web/commit/sha0000000000000000000000000000000000000)) built at 1/1/1970, 1:00:00 AM"  |
| on untagged commit: |  |
| "Version: [1.0.0-dev.1](https://github.com/oasisprotocol/oasis-wallet-web/releases/tag/v1.0.0-dev.1) (commit: …
> Remove release link if current commit doesn't have a tag

- src/app/pages/ParaTimesPage/useParaTimes.test.ts
- src/app/pages/ParaTimesPage/useParaTimes.ts
- src/config.ts
Sync with the latest extension updates
> ParaTimes: enable Sapphire and control order of ParaTimes in a list

- src/app/components/AmountFormatter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AmountFormatter/__tests__/index.test.tsx
- src/app/components/AmountFormatter/index.tsx
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionAmount/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
Copy-pasting balance before: "108.1ROSE"
after: "108.1 ROSE"
> Add a space in AmountFormatter instead of margin

- .mega-linter.yml
- .vscode/settings.json
- src/vendors/explorer/swagger.yml
- src/vendors/oasisscan/swagger.yml
This way we don't need to differentiate them by file name "swagger3.yml" "swagger.yml"
> Inline yaml schemas

- src/app/pages/ParaTimesPage/TransactionAmount/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionAmount/index.tsx
- src/locales/en/translation.json
> ParaTimes: add tooltip to max button

- playwright/tests/persist.spec.ts
- playwright/tests/syncTabs.spec.ts
- src/app/components/Persist/ChoosePasswordFields.tsx
- src/app/components/Sidebar/index.tsx
- src/app/state/selectIsLockableOrCloseable.ts
- src/app/state/selectUnlockedStatus.ts
- src/locales/en/translation.json
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1368
> Update "Close wallet" text for empty skipped-unlocking profile

- src/app/components/Transaction/InfoBox.tsx
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
Currently we attach event handlers to all sections were it doesn't make sense for Time and Block sections
> Don't attach copy handler to all InfoBox components

- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/FatalErrorHandler/index.tsx
- src/app/index.tsx
- src/app/state/account/saga.ts
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1367
| --- | --- |
|  ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90 (1)](https://user-images.githubusercontent.com/3758846/234062784-71217bd6-058f-4a18-a920-a19b33db9ebb.png) |  ![localhost_3000_account_oasis1qrx2z4adfemc3v70cay0fje8jqn4z6wc0500pcn9 (1)](https://user-images.githubusercontent.com/3758846/234063083-1aabe73d-4957-4754-802d-ce9260853076.png) |
> Ignore refetching failures

- internals/getCsp.js
Fixes https://github.com/oasisprotocol/oasis-wallet-web/pull/1431
> Add transak frame-src to CSP

- src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddressBox/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/FatalErrorHandler/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/PrettyAddress/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/PrettyAddress/index.tsx
- src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/index.tsx
- src/app/components/Toolbar/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/TransactionPreview/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
- src/styles/main.css
- src/styles/theme/ThemeProvider.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/pull/1439#discussion_r1188671259
> Make text darker and increase letter-spacing

- playwright/tests/fiat.spec.ts
- src/app/pages/FiatOnrampPage/index.tsx
we now have: Content-Security-Policy, Permissions-Policy, allow=, sandbox=
> Add sandbox to Transak iframe to block top-navigation

- .github/workflows/ci-lint.yml
- .gitlint
- internals/scripts/gitlint.js
- package.json
> Setup gitlint

- .github/workflows/ci-lint.yml
- .markdownlint.yml
- README.md
- docker/oasis-node/README.md
- docs/release-process.md
- package.json
- src/vendors/explorer/README.md
- src/vendors/oasisscan/README.md
- yarn.lock
> Setup markdownlint

- src/styles/theme/ThemeProvider.tsx
| --- | --- |
| ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/91030cb3-29f0-41d3-850b-1da4a81f86dc)  |  ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/30992ae8-d913-42bf-80f8-f653348baa07) |
> Improve tab styling

- src/app/components/Toolbar/Features/Account/Account.tsx
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/index.tsx
- src/app/components/Toolbar/Features/Contacts/ContactAccount.tsx
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/index.tsx
- src/app/components/Toolbar/Features/ScrollableContainer/index.tsx
- src/app/components/Toolbar/Features/layer.ts
- Remove `Box` that is causing overlap issue (when user has many contacts)
- unify scrollable container in Accounts and Contacts
current master
> Contacts overlap issue fix

- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddressFormatter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/FatalErrorHandler/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ResponsiveGridRow/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ThemeSwitcher/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/AddContact.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Profile/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/__tests__/__snapshots__/index.test.tsx.snap
- src/app/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ConnectDevicePage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ConnectDevicePage/index.tsx
- src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
- src/styles/theme/ThemeProvider.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1700
cc @donouwens
> Fix scrolling modals on phone by replacing 100vh with 100dvh

- .github/workflows/ci-build.yml
> Upload build artifacts

- .changelog/1645.process.md
- CHANGELOG.md
- package.json
> Assemble changes for 1.8.0 release

- .changelog/1737.feature.md
- src/app/components/PasswordField/index.tsx
- src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/index.test.tsx
- src/app/pages/ParaTimesPage/TransactionRecipient/index.tsx
- src/app/pages/ParaTimesPage/useParaTimes.ts
- src/app/state/evmAccounts/index.ts
- src/app/state/evmAccounts/selectors.ts
- src/app/state/evmAccounts/types.ts
- src/app/state/paratimes/saga.ts
- src/app/state/persist/index.ts
- src/app/state/persist/saga.ts
- src/app/state/persist/syncTabs.ts
- src/app/state/persist/types.ts
- src/store/reducers.ts
- src/types/RootState.ts
Includes changes from https://github.com/oasisprotocol/oasis-wallet-web/pull/1735
> Suggest previous ethPrivateKeys in ParaTime form

- .changelog/1747.trivial.md
- src/app/components/AddressBox/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddressFormatter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddressFormatter/index.tsx
- src/app/components/AlertBox/index.tsx
- src/app/components/Header/index.tsx
- src/app/components/PrettyAddress/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/PrettyAddress/index.tsx
- src/app/components/ResponsiveGridRow/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ResponsiveGridRow/__tests__/index.test.tsx
- src/app/components/ResponsiveGridRow/index.tsx
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/TransactionModal/index.tsx
- src/app/components/TransactionPreview/index.tsx
- src/app/components/TransactionTypeFormatter/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/locales/en/translation.json
- src/styles/theme/ThemeProvider.tsx
Update based on new designs https://oasisprotocol.clickup.com/t/32df7p7
> Tweak transaction preview modal

- .changelog/1754.trivial.md
- src/app/components/AddEscrowForm/index.tsx
- src/app/components/AddressBox/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddressBox/index.tsx
- src/app/components/AmountFormatter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AmountFormatter/index.tsx
- src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ReclaimEscrowForm/index.tsx
- src/app/components/ResponsiveGridRow/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ResponsiveGridRow/index.tsx
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionAmount/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/CommissionBounds/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/CommissionBounds/index.tsx
- src/app/pages/StakingPage/Features/DelegationList/DelegationItem.tsx
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/ValidatorInformations.tsx
- src/app/pages/StakingPage/Features/ValidatorList/ValidatorItem.tsx
- src/app/pages/StakingPage/Features/ValidatorList/ValidatorStatus.tsx
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorMediaInfo/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorMediaInfo/index.tsx
https://oasisprotocol.clickup.com/t/32df89j
> Tweak mobile validator details view

- .changelog/1762.trivial.md
- renovate.json
> Add TypeScript type definitions group to Renovate bot config

- .changelog/1768.internal.md
- playwright/tests/extension.spec.ts
- playwright/tests/migrating-persisted-state.spec.ts
- playwright/tests/persist.spec.ts
- playwright/tests/syncTabs.spec.ts
- playwright/utils/extensionTestExtend.ts
- playwright/utils/storage.ts
Make things more reusable for ext tests
> Refactor extension tests

- .changelog/1785.internal.md
- playwright/tests/extension.spec.ts
- playwright/tests/fiat.spec.ts
- src/app/components/Transaction/index.tsx
- src/app/state/transaction/types.ts
- src/vendors/oasisscan.ts
- src/vendors/oasisscan/models/OperationsRow.ts
- src/vendors/oasisscan/swagger.yml
Before: cypress CI was failing https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/7045548728/job/19175526654?pr=1784
> Handle new transaction type consensus.Meta

- .changelog/1786.internal.md
- playwright/tests/extension.spec.ts
- playwright/tests/fiat.spec.ts
This reverts commit f6812c5c33e209e545b4c0a46839b09b73993c2e.
> Re-enable Transak tests (merge when Transak is fixed)

- .changelog/1777.trivial.md
- src/app/components/BuildBanner/index.tsx
- src/locales/en/translation.json
Reverts most of commit 9cb52a85604d216119df91de94c9574559db6784.
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/1530
cc @donouwens
> Remove new domain banner

- .changelog/1788.trivial.md
- renovate.json
See https://github.com/oasisprotocol/oasis-wallet-web/pull/1764, it included "@typescript-eslint/eslint-plugin"
> Fix renovate @type/ group

- .changelog/1802.trivial.md
- src/app/components/TransactionPreview/index.tsx
| --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/ec3d822a-6117-4683-9442-62542f0539b3)  |  ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/cf09a455-fb17-4d16-80a6-1da517912f78) |
> Display gas limit in raw units instead of gigaunits

- .changelog/1798.trivial.md
- src/app/components/Toolbar/Features/ProfileModalButton/index.tsx
- src/locales/en/translation.json
| --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension360x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/e72962b4-3827-42e0-ae59-afae91bcfa36) | ![localhost_3000_(extension360x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/be96555f-7145-4f92-acb8-14f6c6b663b6)  |
> Add a button to Add accounts in My Accounts settings

- .changelog/1806.bugfix.md
- src/app/components/ResponsiveLayer/index.tsx
- src/app/components/Toolbar/Features/Account/ManageableAccountDetails.tsx
- src/app/components/Toolbar/Features/Contacts/AddContact.tsx
- src/app/components/Toolbar/Features/Contacts/ContactAccount.tsx
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/AddContact.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/index.tsx
- src/app/components/Toolbar/Features/LayerContainer/index.tsx
- src/app/components/Toolbar/Features/Profile/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Profile/index.tsx
- src/app/components/Toolbar/Features/ProfileModalButton/index.tsx
- src/app/components/Toolbar/Features/Settings/index.tsx
- src/app/components/Toolbar/Features/layer.ts
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
- src/styles/theme/ThemeProvider.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1776
| --- | --- |
| ![My-Accounts-tab-should-get-a-private-key-1-chromium-linux](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/bc4838eb-0b31-4c47-bec6-bf575d07402d) | ![My-Accounts-tab-should-get-a-private-key-1-chromium-linux](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/6b5bc0d6-01cd-496e-a3d7-82aaae3eae2c) |
| ![My-Accounts-tab-should-get-a-private-key-2-chromium-linux](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/aa7ec06b-4b3d-4eda-a478-73b685aa58dd) | ![My-Accounts-tab-should-get-a-private-key-2-chromium-linux](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/a8017faf-06fa-4dec-90ae-9382d0db3eb5) |
| …
> Refactor layerOverlayMinHeight to avoid needless scrollbars

- .changelog/1810.trivial.md
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/index.tsx
| --- | --- |
| ![Screenshot from 2023-12-19 01-28-14](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/11481ffb-507b-4385-bb7c-87971a102eb4)  |  ![Screenshot from 2023-12-19 01-27-56](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/1b630f51-bdfe-4767-a323-8d9baced59ac) |
> Fix account selector layout

- .changelog/1814.internal.md
- src/app/pages/CreateWalletPage/slice/index.ts
- src/app/pages/FiatOnrampPage/slice/index.ts
- src/app/state/account/index.ts
- src/app/state/contacts/index.ts
- src/app/state/evmAccounts/index.ts
- src/app/state/fatalerror/index.ts
- src/app/state/importaccounts/index.ts
- src/app/state/network/index.ts
- src/app/state/paratimes/index.ts
- src/app/state/persist/index.ts
- src/app/state/persist/syncTabs.ts
- src/app/state/staking/index.ts
- src/app/state/transaction/index.ts
- src/app/state/wallet/index.ts
- src/store/reducers.ts
- src/store/slices.ts
- src/styles/theme/slice/index.ts
This should detect: https://github.com/oasisprotocol/oasis-wallet-web/pull/1735/files#r1366593848
I think it was one of the main pitfalls with syncing and persisting
> Explicitly mark each action and slice for syncing and persisting

- .changelog/1824.feature.md
- src/app/components/MobileFooterNavigation/__tests__/index.test.tsx
- src/app/components/MobileFooterNavigation/index.tsx
- src/app/components/Sidebar/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Sidebar/__tests__/index.test.tsx
- src/app/components/Sidebar/index.tsx
- src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/__tests__/index.test.tsx
- src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/index.tsx
- src/app/pages/ParaTimesPage/__tests__/index.test.tsx
- src/app/pages/ParaTimesPage/index.tsx
- src/app/pages/ParaTimesPage/useParaTimesNavigation.ts
- src/locales/en/translation.json
- src/locales/sl/translation.json
- src/locales/tr/translation.json
- src/locales/zh_CN/translation.json
| --- | --- |
| ![localhost_3000_account_oasis1qrf4y7aelwuusc270e8qx04ysr45w3q0zyavrpdk_paratimes (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/0e385949-101d-40c1-b3e2-363ee46fd427) | ![localhost_3000_account_oasis1qrf4y7aelwuusc270e8qx04ysr45w3q0zyavrpdk_paratimes](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/44467fcf-da0a-4033-adc1-fcc86b51fec5) |
> Show a link to disabled ParaTimes page on Ledger accounts

- .changelog/1616.internal.md
- .changelog/1725.internal.md
- .changelog/1732.internal.md
- .changelog/1733.internal.md
- .changelog/1742.internal.md
- .changelog/1743.internal.md
- .changelog/1744.internal.md
- .changelog/1745.internal.md
- .changelog/1746.internal.md
- .changelog/1750.internal.md
- .changelog/1758.internal.md
- .changelog/1759.internal.md
- .changelog/1765.internal.md
- .changelog/1766.internal.md
- .changelog/1789.internal.md
- .changelog/1793.internal.md
- .changelog/1795.internal.md
- .changelog/1800.internal.md
- .changelog/1801.internal.md
- .changelog/1803.internal.md
- .changelog/1804.internal.md
- .changelog/1835.internal.md
- .github/workflows/ci-renovate.yml
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1730
> Group all renovate dependency updates under one Changelog entry

- .changelog/1836.feature.md
- src/app/components/Persist/DeleteProfileButton.tsx
- src/app/components/Persist/UnlockForm.tsx
- src/app/components/Toolbar/Features/Account/ManageableAccountDetails.tsx
| --- | --- |
| ![localhost_3000_account_oasis1qrnzhcl8nap2f0p730qeedmjmuhtw9hnhv6urnee(extension360x600) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/fddecdeb-9d41-4b1f-92cb-c9bb9bccd809) | ![localhost_3000_account_oasis1qrnzhcl8nap2f0p730qeedmjmuhtw9hnhv6urnee(extension360x600) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/6b2f1601-eb95-4b03-af73-aa04931e477f) |
| ![localhost_3000_account_oasis1qrnzhcl8nap2f0p730qeedmjmuhtw9hnhv6urnee(extension360x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/33235112-1c67-480c-8c04-4f754dfebd6f) | ![localhost_3000_account_oasis1qrnzhcl8nap2f0p730qeedmjmuhtw9hnhv6urnee(extension360x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/a48e3a45-5d …
> Improve Delete Account button layout on mobile

- .changelog/1838.feature.md
- src/app/components/Toolbar/Features/Account/Account.tsx
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
Includes https://github.com/oasisprotocol/oasis-wallet-web/pull/1837
| --- | --- |
| ![localhost_3000_account_oasis1qpp0gmh4fug8qnrz8ca233nmvxqlcw6vechczper(iPhone XR)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/f07b3846-601c-49a4-9959-02b6b947b686) | ![localhost_3000_account_oasis1qpp0gmh4fug8qnrz8ca233nmvxqlcw6vechczper(iPhone XR) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/754c45c7-684e-4c95-b6cf-7aabad5432a2) |
> Move balance into the same row as Manage button on mobile

- .changelog/1850.bugfix.md
- internals/jest/setupTests.ts
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/index.test.tsx
- src/app/components/Toolbar/Features/AccountSelector/index.tsx
- src/app/components/Toolbar/Features/Profile/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Profile/index.tsx
- src/app/components/Toolbar/Features/ProfileModalButton/__tests__/index.test.tsx
- src/app/components/Toolbar/Features/ProfileModalButton/index.tsx
| --- | --- |
| ![wallet dev oasis io_account_oasis1qzwmjwt5nwv6e37kjmnj59yx7kvnsg4q5cga3580(extension360x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/822075d1-4c58-4a81-9c17-cea8b6e2cb4d) | ![localhost_3000_account_oasis1qzwmjwt5nwv6e37kjmnj59yx7kvnsg4q5cga3580(extension360x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/4ea4fb2b-342a-4e06-be76-012448bfa4c5) |
| ![wallet dev oasis io_account_oasis1qzwmjwt5nwv6e37kjmnj59yx7kvnsg4q5cga3580(extension360x600) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/469ca533-014e-43b2-8c31-647a60fbf900) | ![localhost_3000_account_oasis1qzwmjwt5nwv6e37kjmnj59yx7kvnsg4q5cga3580(extension360x600) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/4 …
> Update buttons layout in mobile settings and fix double scrollbar in extension

- .changelog/1857.trivial.md
- internals/jest/setupTests.ts
- src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddEscrowForm/index.tsx
- src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ReclaimEscrowForm/index.tsx
- src/app/pages/AccountPage/Features/SendTransaction/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
| --- | --- |
| ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/f186de3d-db9c-467a-a4d7-e7283442d6d7)  |  ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/f6a17cb9-7aab-43a3-8e4c-ff976256b5cd) |
> Show ticker hint in inputs

- .changelog/1859.trivial.md
- src/app/components/FatalErrorHandler/index.tsx
- src/locales/en/translation.json
- src/styles/theme/ThemeProvider.tsx
https://app.clickup.com/t/8693qqdp3
> Update fatal error designs

- .changelog/1864.bugfix.md
- src/app/pages/ParaTimesPage/ParaTimeContent/index.tsx
- src/app/pages/ParaTimesPage/ParaTimeSelection/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/ParaTimeSelection/index.tsx
- src/app/pages/ParaTimesPage/ParaTimeTransferType/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionAmount/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionConfirmation/index.tsx
- src/app/pages/ParaTimesPage/TransactionError/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionError/index.tsx
- src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionSummary/__tests__/__snapshots__/index.test.tsx.snap
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1862
| --- | --- |
|  ![wallet oasis io_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/937d5762-f874-4c91-88a1-630aa1f22663) | ![wallet oasis io_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/937d5762-f874-4c91-88a1-630aa1f22663)  |
| ![wallet oasis io_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes(extension360x600) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/2972ffff-d6bb-4d31-b304-fad54cb46433) | ![wallet oasis io_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_paratimes(extension360x600)](ht …
> Fix long strings overflowing their container in extension layout

- .changelog/1865.internal.md
- playwright/tests/extension.spec.ts
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1860 and https://github.com/oasisprotocol/oasis-wallet-web/issues/1853
> E2E test recovering from fatal errors in extension

- .changelog/1866.trivial.md
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/locales/de/translation.json
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/fr/translation.json
- src/locales/sl/translation.json
- src/locales/tr/translation.json
- src/locales/zh_CN/translation.json
| --- | --- |
| ![localhost_3000_account_oasis1qz5ln8gglx7qf378e5x760y6jlkd9tm79g2tc592](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/63caee21-12a1-4061-950f-1c385ebd5eed) | ![localhost_3000_account_oasis1qq9sdfk52u966nwx3sunm7matlfaq63cfgd9mtr5](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/95219ec6-98e6-48b3-bd92-8ad223a03115) |
| ![localhost_3000_account_oasis1qz5ln8gglx7qf378e5x760y6jlkd9tm79g2tc592 (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/b04ce10a-dc26-4e6b-a49b-971f76d361aa) | ![localhost_3000_account_oasis1qq9sdfk52u966nwx3sunm7matlfaq63cfgd9mtr5 (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/73bed107-88a1-41d1-86d8-e6e96caddcb1) |
> Remove "This is your account" banner

- .changelog/1875.internal.md
- playwright/tests/extension.spec.ts
- playwright/tests/fiat.spec.ts
It doesn't seem like they're fixing it fast.
> Ignore transak's CSP errors that are not caused by our CSP

- .changelog/1874.trivial.md
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/ScrollableContainer/index.tsx
| --- | --- |
|  ![Screenshot from 2024-04-05 22-58-12](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/e466e629-4aa5-4887-8fea-c281adc2b9ca)  |  ![Screenshot from 2024-04-05 22-57-34](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/be21169e-b115-43f1-96af-f1245f63487f) |
> Fix focus indicator clipping in ScrollableContainer

- .changelog/1878.bugfix.md
- playwright/tests/syncTabs.spec.ts
- src/app/components/Sidebar/index.tsx
- src/app/pages/AccountPage/Features/AccountDetails/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
| --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/7a874c48-9c93-40f2-9e98-f40a547c94c1) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/df8d49f2-fcf9-4379-8950-a5f164aaea91) |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (3)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/d8a2294c-900a-45bd-bb6b-6096232f8739) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (2)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/592d7a29-9b9c-4643-8889-5de393e5fdd2) |
> Show expanded sidebar on medium size devices too

- .changelog/1884.trivial.md
- src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Footer/index.tsx
- src/locales/en/translation.json
This reverts commit 0350a9a5075987bfc2a8efeeb5a3b6ea85038b2e.
> Revert "Add ROSE trademark notice"

- .changelog/1888.trivial.md
- src/app/pages/ParaTimesPage/ParaTimeContent/index.tsx
- src/app/pages/ParaTimesPage/ParaTimeSelection/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/ParaTimeSelection/index.tsx
- src/app/pages/ParaTimesPage/ParaTimeTransferType/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/ParaTimesPageInaccessible/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionAmount/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionConfirmation/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionConfirmation/index.tsx
- src/app/pages/ParaTimesPage/TransactionError/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionError/index.tsx
- src/app/pages/ParaTimesPage/TransactionRecipient/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ParaTimesPage/TransactionSummary/__tests__/__snapshots__/index.test.tsx.snap
Follows #1864 ? 
current master
> Fix ParaTime transfer confirmation layout

- .changelog/1886.bugfix.md
- playwright/tests/refreshing-balance.spec.ts
- src/app/state/account/saga.test.ts
- src/app/state/account/saga.ts
> Update wallet store balance while fetching account details

- .changelog/1892.bugfix.md
- src/config.ts
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1891
> Adjust gas limit for Cipher deposits and withdrawals

- .changelog/1897.bugfix.md
- src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Footer/index.tsx
Related https://github.com/oasisprotocol/internal-ops/pull/197
> Update Terms and Conditions and fix opening it on Windows

- .changelog/1908.bugfix.md
- src/app/pages/FiatOnrampPage/index.tsx
- src/styles/theme/ThemeProvider.tsx
| --- | --- |
|  ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_fiat](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/dd598229-30d7-4de4-b8e0-ecf0e5bab432) |  ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_fiat(extension375x600)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/2f3fd4d4-e84f-47dd-86ba-63a5d6906f6c) |
> Restyle Transak notices

- .changelog/1913.bugfix.md
- playwright/tests/persist.spec.ts
- playwright/tests/preventSavingInputsToDisk/chromium.spec.ts
- playwright/tests/preventSavingInputsToDisk/firefox.spec.ts
- playwright/utils/fillPrivateKey.ts
- src/app/components/AddEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Persist/ChoosePasswordFields.tsx
- src/app/components/ReclaimEscrowForm/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/ThemeSwitcher/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/AddContact.test.tsx.snap
- src/app/components/Toolbar/Features/Profile/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/CreateWalletPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/__snapshots__/index.test.tsx.snap
- src/locales/en/translation.json
- src/styles/theme/ThemeProvider.tsx
| --- | --- |
|  ![before](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/28700379-5fca-4ba3-b1a7-f5c38d8e18bf) | ![localhost_3000_create-wallet(extension375x600 + scrollbar)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/54f19379-b63a-4c49-a797-34b3bb666339)  |
Mocks:
> Improve the text for creating a profile

- .changelog/1904.bugfix.md
- src/app/components/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Header/index.tsx
- src/app/components/Persist/DeleteProfileButton.tsx
- src/app/components/Persist/LoginModalLayout.tsx
- src/app/components/Persist/MigrateV0StateForm.tsx
- src/app/components/Persist/UnlockForm.tsx
- src/app/pages/ConnectDevicePage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/ConnectDevicePage/index.tsx
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/__snapshots__/index.test.tsx.snap
| --- | --- |
|  ![Screenshot from 2024-04-24 23-09-25](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/bc504320-1cf7-442a-a473-6201f8465ae7) |  ![Screenshot from 2024-04-24 23-07-14](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/19b138ad-fef2-4deb-8b0c-83dbe296a10d) |
> Add logo to login form

- .changelog/1920.bugfix.md
- src/app/components/AddressBox/index.tsx
- src/app/components/Transaction/InfoBox.tsx
> Fix layout when showing notifications

- .changelog/1916.trivial.md
- src/app/components/Toolbar/Features/Profile/UpdatePassword.tsx
- src/app/components/Toolbar/Features/Profile/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Profile/index.tsx
- src/locales/en/translation.json
| --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/bf47e4bb-1425-45a9-9b50-c52ed8eb5461)  | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/b6781351-e879-400d-8365-2a9dc5f40312)  |
> Align "Update password" button to the left

- .changelog/1914.feature.md
- playwright/tests/persist.spec.ts
- playwright/tests/syncTabs.spec.ts
- src/app/components/Persist/UnlockForm.tsx
- src/locales/en/translation.json
Related to https://github.com/oasisprotocol/oasis-wallet-web/issues/1861
| --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar) (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/e523488c-0466-4770-9335-d077dec8e6a1)  |  ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/223f4ca2-80e7-4e90-9c55-d764ebfb06b4) |
> Remove incognito mode button (haven't removed all the related code)

- .changelog/1928.bugfix.md
- android/app/capacitor.build.gradle
- android/capacitor.settings.gradle
- ios/App/Podfile
- package.json
- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Ionic/IonicProvider.tsx
- src/app/index.tsx
- yarn.lock
Current behavior of physical back button on Android is unexpected. Back button was closing the app, which is not the expected behavior. This correctly integrates with `react-router-dom` to navigate one page in history back and only closes the app, if there is no history.
https://github.com/oasisprotocol/oasis-wallet-web/assets/9722540/448d4168-03c1-4a1f-944d-e19d03e669e7
> Fix physical back button behavior on Android

- .changelog/1935.bugfix.md
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/AddContact.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Profile/UpdatePassword.tsx
- src/app/components/Toolbar/Features/Profile/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/ScrollableContainer/index.tsx
- src/app/components/Toolbar/Features/layer.ts
| --- | --- |
|    https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/cc79c188-d80c-4ae5-9a0b-a984026e5d84    |  https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/79f541ce-0eac-477c-8b54-8a759a448cae      |
> Make settings tabs consistent height

- .changelog/1950.bugfix.md
- src/app/components/Toolbar/Features/Contacts/index.tsx
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1920
Before:
> Stop settings dialog resizing when clicking "Add contact"

- .changelog/1962.trivial.md
- src/app/components/Toolbar/Features/Account/DeleteAccount.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/pull/1953
> Fix using bold text instead of quotes around "delete"

- .changelog/1956.bugfix.md
- playwright/tests/transfer.spec.ts
- src/app/components/AddEscrowForm/index.tsx
- src/app/components/ReclaimEscrowForm/index.tsx
- src/app/lib/__tests__/usePreventChangeOnNumberInputScroll.test.tsx
- src/app/lib/usePreventChangeOnNumberInputScroll.ts
- src/app/pages/AccountPage/Features/SendTransaction/index.tsx
- src/app/pages/ParaTimesPage/TransactionAmount/FeesSection.tsx
Resolves https://github.com/oasisprotocol/oasis-wallet-web/issues/1955
> Prevent value change on number input wheel scroll

- .changelog/1966.bugfix.md
- playwright/tests/extension.spec.ts
- src/app/pages/FiatOnrampPage/index.tsx
- src/locales/en/translation.json
If extension popup closes you lose all progress and it's too small to fit embedded widget.
| --- | --- |
| ![wallet dev oasis io_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_fiat0](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/651bd3c5-5e50-4711-92f7-0285c9e47098) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_fiat](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/df942195-6ea5-48c3-82a7-06fdc31beb04) |
| ![wallet dev oasis io_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_fiat1](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/c8a2419e-6f4b-45b4-bfea-33f5a145eac3) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_fiat …
> Restyle "Buy ROSE" page and open Transak in new tab on small screens

- .changelog/1977.trivial.md
- playwright/tests/extension.spec.ts
- src/app/components/FatalErrorHandler/index.tsx
- src/app/pages/FiatOnrampPage/index.tsx
- src/locales/en/translation.json
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1972
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1880
> Always show Reload button on fatal error (for recovering in mobile app)

- .changelog/1988.trivial.md
- cypress/e2e/create-wallet.cy.ts
- cypress/e2e/open-wallet.cy.ts
- cypress/e2e/scenario-account-switcher.cy.ts
- cypress/e2e/scenario-transaction.cy.ts
- playwright/tests/persist.spec.ts
- playwright/tests/preventSavingInputsToDisk/chromium.spec.ts
- playwright/tests/preventSavingInputsToDisk/firefox.spec.ts
- playwright/tests/syncTabs.spec.ts
- playwright/tests/toolbar.spec.ts
- src/app/components/MnemonicValidation/index.tsx
- src/app/pages/CreateWalletPage/__tests__/index.test.tsx
- src/app/pages/CreateWalletPage/index.tsx
- src/locales/de/translation.json
- src/locales/en/translation.json
https://app.clickup.com/t/8694m4w9p
> Rename keyphrase to mnemonic

- .changelog/1986.bugfix.md
- src/app/components/MobileFooterNavigation/index.tsx
- src/app/components/Sidebar/index.tsx
- src/app/pages/AccountPage/Features/StakeSubnavigation/index.tsx
- src/commonRoutes.tsx
Built on top of https://github.com/oasisprotocol/oasis-wallet-web/pull/1985
Fixes part of https://github.com/oasisprotocol/oasis-wallet-web/issues/276
> Make Stake button active in delegations and debonding routes

- .changelog/1994.trivial.md
- src/app/components/Transaction/index.tsx
> Style failed transactions more noticeably

- .changelog/1995.trivial.md
- package.json
- src/app/components/CountdownButton/index.tsx
- src/app/lib/helpers.ts
- yarn.lock
Similar to ACCOUNT_REFETCHING_INTERVAL
> Speedup CountdownButton in tests

- .changelog/1989.trivial.md
- src/app/components/Toolbar/Features/Account/Account.tsx
- src/app/components/Toolbar/Features/Account/DerivationFormatter.tsx
- src/app/components/Toolbar/Features/Account/ImportableAccount.tsx
- src/app/components/Toolbar/Features/Account/ManageableAccount.tsx
- src/app/components/Toolbar/Features/Account/ManageableAccountDetails.tsx
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
- src/locales/de/translation.json
- src/locales/en/translation.json
- src/locales/sl/translation.json
- src/locales/tr/translation.json
- src/locales/zh_CN/translation.json
- src/styles/theme/icons/mui-icons/MuiBluetoothIcon.tsx
- src/styles/theme/icons/mui-icons/MuiMarginIcon.tsx
- src/styles/theme/icons/mui-icons/MuiUsbIcon.tsx
- src/styles/theme/icons/mui-icons/MuiVpnKeyIcon.tsx
https://app.clickup.com/t/8694m4gwj
> Show account derivation paths in settings

- .changelog/2004.trivial.md
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/index.tsx
Slight improvement until we convert away from tables
| --- | --- |
| ![wallet dev oasis io_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_stake_active-delegations(extension375x600 + scrollbar)](https://github.com/user-attachments/assets/e08e7b0e-0cbf-49f4-a1a2-b24765fe46cc) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_stake_active-delegations(extension375x600 + scrollbar)](https://github.com/user-attachments/assets/58ed103e-5282-49e1-b3f7-6ab8e6a80325) |
| ![wallet dev oasis io_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km_stake_active-delegations(extension375x600 + scrollbar) (1)](https://github.com/user-attachments/assets/c6967388-9dc1-46a5-91bd-33d3a1c347ea) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n4 …
> Improve delegation and debonding tables in extension layout

- .changelog/2009.trivial.md
- src/app/pages/AccountPage/Features/StakeSubnavigation/index.tsx
- src/app/pages/AccountPage/Features/TransactionHistory/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/ActiveDelegationList.tsx
- src/app/pages/StakingPage/Features/DelegationList/DebondingDelegationList.tsx
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/index.tsx
- src/locales/en/translation.json
> Remove headings from staking subpages

- .changelog/2005.trivial.md
- playwright/tests/validators.spec.ts
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
| --- | --- |
| ![image](https://github.com/user-attachments/assets/4fd6fa05-8f18-41d9-b02b-c6eb3a1ad52c)       |     ![image](https://github.com/user-attachments/assets/c5a7ac09-001c-4bf7-821f-065bb215b878) |
> Make Total balance font-size equal to other balance fields

- .changelog/2010.trivial.md
- src/app/components/AddressFormatter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddressFormatter/index.tsx
- src/app/components/Transaction/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Transaction/index.tsx
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/2003
| --- | --- |
| ![localhost_3000_account_oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm(extension375x600 + scrollbar) (1)](https://github.com/user-attachments/assets/95e17f29-6e0c-4660-bc59-2014d6ab85f1) | ![localhost_3000_account_oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm(extension375x600 + scrollbar)](https://github.com/user-attachments/assets/90a03dd9-e732-4699-99cf-abedb7cdf5bf) |
> Make more transaction fields smaller

- .changelog/2008.bugfix.md
- src/app/pages/CreateWalletPage/index.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1714
> Fix losing mnemonic input when changing phone orientation

- .changelog/2011.trivial.md
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/locales/en/translation.json
Related to https://github.com/oasisprotocol/oasis-wallet-web/issues/965#issuecomment-1252005022
> Add translations to empty delegations table

- .changelog/2012.trivial.md
- src/app/pages/AccountPage/Features/SendTransaction/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
> Add "Send" heading above SendTransaction form

- .changelog/2015.trivial.md
- src/app/components/AddressBox/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/AddressBox/__tests__/index.test.tsx
- src/app/components/AddressBox/index.tsx
- src/app/pages/AccountPage/Features/AccountSummary/index.tsx
- src/app/pages/AccountPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/pages/AccountPage/__tests__/index.test.tsx
- src/app/pages/StakingPage/Features/ValidatorList/ValidatorInformations.tsx
https://app.clickup.com/t/8694m4b46
> Improve display of unnamed account addresses

- .changelog/2018.trivial.md
- src/app/components/MobileFooterNavigation/index.tsx
- src/app/components/Sidebar/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Sidebar/index.tsx
- src/app/pages/AccountPage/Features/StakeSubnavigation/index.tsx
| --- | --- |
| ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_stake (1)](https://github.com/user-attachments/assets/992c8ab3-27da-4c88-ab58-61ca58225c2c) | ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_stake](https://github.com/user-attachments/assets/44ee0bc1-139e-4ac6-95af-cdec4dd0ccdc) |
| ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_stake(extension375x600 + scrollbar) (1)](https://github.com/user-attachments/assets/eb845170-b17f-4dd2-9c4a-e5f203fc9b43) | ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_stake(extension375x600 + scrollbar)](https://github.com/user-attachments/assets/70023e0f-f7a4-4f1e-8347-49e514ce6a10) |
> Consistently style active and hovered buttons in nav bars

- .changelog/2019.trivial.md
- src/app/components/ThemeSwitcher/index.tsx
- src/app/pages/StakingPage/Features/DelegationList/index.tsx
- src/locales/en/translation.json
Incorrectly changed in d373356df291f500ad808c30eaefd49a2fa5c698.
> Fix theme switcher icon size

- .changelog/2024.bugfix.md
- src/app/components/LanguageSelect/index.tsx
- src/app/components/Sidebar/index.tsx
- src/app/components/Toolbar/Features/Account/Account.tsx
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/NetworkSelector/index.tsx
- src/styles/theme/ThemeProvider.tsx
| --- | --- |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (2)](https://github.com/user-attachments/assets/7c5ec773-0ac0-4476-9012-39f0b9659dbd) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km](https://github.com/user-attachments/assets/43a398db-ebe3-438c-a0f0-5b23c94eb3d8) |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (3)](https://github.com/user-attachments/assets/238faed3-e4f8-454d-a179-450e48f157dd) | ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km (1)](https://github.com/user-attachments/assets/0ee594c1-55db-4a31-9c46-495a96e343e4) |
| ![localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km …
> Change menu colors

- .changelog/2028.trivial.md
- src/app/components/Toolbar/Features/Account/__tests__/__snapshots__/Account.test.tsx.snap
- src/app/components/Toolbar/Features/AccountSelector/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Toolbar/Features/Contacts/__tests__/__snapshots__/index.test.tsx.snap
- src/styles/theme/ThemeProvider.tsx
> Make background hover indicator on menu items darker in light theme

- .changelog/2040.bugfix.md
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/ActiveDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/DelegationList/__tests__/__snapshots__/DebondingDelegationList.test.tsx.snap
- src/app/pages/StakingPage/Features/ValidatorList/__tests__/__snapshots__/index.test.tsx.snap
- src/types/TypeSafeDataTable.tsx
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/1858
Alternative to https://github.com/oasisprotocol/oasis-wallet-web/pull/2034
> Fix expanding table rows on non-plaintext cell

- .changelog/2049.process.md
- .github/workflows/dump-validators.yml
- .github/workflows/update-screenshots.yml
Related to https://github.com/oasisprotocol/wallet/pull/2044
> Add monthly cron job to update screenshots

- .changelog/2057.process.md
- .github/workflows/cloudflare-pages.yml
Related to https://github.com/oasisprotocol/explorer/issues/561 and https://github.com/oasisprotocol/explorer/pull/1537
> Cloudflare stable preview URLs

- .changelog/2059.trivial.md
- src/app/components/ErrorFormatter/index.tsx
- src/app/state/wallet/saga.ts
| --- | --- |
| ![localhost_3000_open-wallet_ledger_usb](https://github.com/user-attachments/assets/eaa38506-5dfc-47c5-88b7-20eaa2df83d3) | ![localhost_3000_open-wallet_ledger_usb (1)](https://github.com/user-attachments/assets/6428368f-6237-4606-8a33-b9a56c72f42c) |
> Fix ledger error text line breaks

- .changelog/2106.bugfix.md
- src/config.ts
Fixes https://github.com/oasisprotocol/wallet/pull/2075
> Fix Oasis Scan V2 testnet API url

- .changelog/2096.internal.md
- .github/workflows/ci-build.yml
- playwright/tests/extension.spec.ts
- playwright/tests/home.spec.ts
- playwright/tests/paraTimes.spec.ts
- playwright/tests/persist.spec.ts
- playwright/tests/preventSavingInputsToDisk/chromium.spec.ts
- playwright/tests/preventSavingInputsToDisk/firefox.spec.ts
- playwright/tests/refreshing-balance.spec.ts
- playwright/tests/syncTabs.spec.ts
- playwright/tests/transfer.spec.ts
- playwright/tests/validators.spec.ts
- playwright/utils/mockApi.ts
Closes https://github.com/oasisprotocol/wallet/issues/2090
> Switch to Nexus mocks in Playwright

- .changelog/2098.internal.md
- .env
- src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
~Waits for Nexus and nexus.oasis.io DNS switch~
> Use Nexus API as ROSE Wallet backend

- .changelog/2097.doc.md
- docs/mobile.md
Move tutorial from https://github.com/oasisprotocol/wallet/pull/1944 to Wallet mobile docs and add notes about certificate validity flag.
> Explain Android app signing key configuration and secret management

- .changelog/2124.internal.md
- src/app/pages/CreateWalletPage/index.tsx
- src/app/pages/OpenWalletPage/Features/FromBleLedger/index.tsx
- src/app/pages/OpenWalletPage/Features/FromMnemonic/index.tsx
- src/app/pages/OpenWalletPage/Features/FromUsbLedger/index.tsx
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/__tests__/index.test.tsx
- src/app/pages/OpenWalletPage/Features/ImportAccountsSelectionModal/index.tsx
- src/app/pages/OpenWalletPage/__tests__/index.test.tsx
- src/app/pages/OpenWalletPage/index.tsx
- src/app/state/wallet/saga.ts
Part of https://github.com/oasisprotocol/wallet/issues/2114
> Harden code against wrong imported account type

- .changelog/2123.bugfix.md
- src/app/state/account/saga.test.ts
- src/app/state/account/saga.ts
- src/app/state/account/selectors.ts
- src/app/state/transaction/saga.ts
- src/app/state/wallet/saga.test.ts
- src/app/state/wallet/saga.ts
- src/vendors/nexus.ts
Fixes https://github.com/oasisprotocol/wallet/issues/2113
> Fix paratime transaction status in the first few seconds

- .changelog/2128.bugfix.md
- src/app/state/account/index.ts
- src/app/state/account/types.ts
- src/app/state/transaction/saga.test.ts
- src/app/state/transaction/saga.ts
Fixes https://github.com/oasisprotocol/wallet/pull/2123#pullrequestreview-2640345847
> Show ParaTime transactions in pending transactions section

- .changelog/2142.trivial.md
- src/app/pages/ParaTimesPage/useParaTimes.test.ts
- src/config.ts
Closes https://github.com/oasisprotocol/wallet/issues/2141
>  Update paratimes display order

- .changelog/2144.bugfix.md
- src/config.ts
Closes https://github.com/oasisprotocol/wallet/issues/2143
> Fix Explorer link for testnet network

- .changelog/2149.bugfix.md
- extension/src/ExtLedgerAccessPopup/ExtLedgerAccessPopup.tsx
- extension/src/ExtLedgerAccessPopup/__tests__/index.test.tsx
- src/app/components/ErrorFormatter/index.tsx
- src/app/pages/E2EPage/index.tsx
Fixes https://github.com/oasisprotocol/wallet/issues/2150 and https://github.com/oasisprotocol/wallet/issues/2151
Before
https://github.com/user-attachments/assets/24991cf1-7e59-4da4-be74-00616ea80c67 
After
https://github.com/user-attachments/assets/2bf1fec8-cca8-46a6-9c72-09bd73a0768a
> Show Ledger help links on USBTransportError and in extension

- .changelog/2156.bugfix.md
- src/app/components/AmountFormatter/index.tsx
- src/app/components/Transaction/index.tsx
- src/config.ts
- src/locales/en/translation.json
- src/locales/sl/translation.json
https://wallet.dev.oasis.io/account/oasis1qppz78n4lpnw9knz7d7jz7vvjrt7qd2c6ypsa7me
| --- | --- |
|  ![Screenshot from 2025-03-24 22-26-03](https://github.com/user-attachments/assets/96f19040-6dec-411a-a5c3-d4732e361c58)      |       ![Screenshot from 2025-03-24 22-11-40](https://github.com/user-attachments/assets/bff04f0a-6d14-4b05-800b-81b1f671686f) |
> Improve description of allowance change transactions

- .changelog/2165.internal.md
- playwright/tests/monitor-consensus-transfer-fee.spec.ts
- src/app/pages/E2EPage/E2EWindow.d.ts
- src/app/pages/E2EPage/index.tsx
Intermediate step until we fix hardcoded `setFeeAmount(oasis.quantity.fromBigInt(0n))`
Related to https://github.com/oasisprotocol/wallet/pull/2081
> Test hardcoded Consensus transaction fee

- .changelog/2171.trivial.md
- src/app/components/PasswordField/index.tsx
- src/app/pages/ParaTimesPage/TransactionRecipient/index.tsx
- src/locales/en/translation.json
> Add instructions inside eth private key dropdown

- .changelog/1694.internal.md
- .changelog/1799.internal.md
- .changelog/1854.internal.md
- .changelog/1958.internal.md
- .changelog/2128.bugfix.md
- .changelog/2131.feature.md
- .changelog/2133.internal.txt
- .changelog/2137.bugfix.md
- .changelog/2142.trivial.md
- .changelog/2144.bugfix.md
- .changelog/2145.bugfix.md
- .changelog/2146.internal.md
- .changelog/2148.bugfix.md
- .changelog/2149.bugfix.md
- .changelog/2154.bugfix.md
- .changelog/2155.trivial.md
- .changelog/2156.bugfix.md
- .changelog/2161.internal.md
- .changelog/2165.internal.md
- .changelog/2166.internal.md
- .changelog/2167.internal.md
- .changelog/2169.trivial.md
- .changelog/2170.internal.md
- .changelog/2171.trivial.md
- .changelog/2172.internal.md
- CHANGELOG.md
- package.json
- public/manifest.json
Lets do a release before https://github.com/oasisprotocol/wallet/pull/2174 and https://github.com/oasisprotocol/wallet/pull/2173 in case something breaks
> Assemble changes for 2.3.0 release

- .changelog/2182.bugfix.md
- .parcelrc
Supersedes https://github.com/oasisprotocol/wallet/pull/2180
Broken since https://github.com/oasisprotocol/wallet/pull/2174
> Fix importing images in parcel@2.14

- .changelog/2205.bugfix.md
- extension/src/ExtLedgerAccessPopup/ExtLedgerAccessPopup.tsx
- src/app/components/ErrorFormatter/index.tsx
- src/app/pages/OpenWalletPage/Features/FromLedger/index.tsx
- src/app/state/importaccounts/saga.ts
- src/locales/en/translation.json
- src/types/errors.ts
- src/types/typed-redux-runSaga.d.ts
Includes commits from https://github.com/oasisprotocol/wallet/pull/2201
Related https://github.com/oasisprotocol/wallet/issues/2198
> Detect faulty Ledger firmware
